// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/reputation/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the reputation module's genesis state.
type GenesisState struct {
	// reputation_scores is the list of all reputation scores at genesis.
	ReputationScores []ReputationScore `protobuf:"bytes,1,rep,name=reputation_scores,json=reputationScores,proto3" json:"reputation_scores"`
	// feedbacks is the list of all feedbacks at genesis.
	Feedbacks []Feedback `protobuf:"bytes,2,rep,name=feedbacks,proto3" json:"feedbacks"`
	// params defines the module parameters at genesis.
	Params Params `protobuf:"bytes,3,opt,name=params,proto3" json:"params"`
	// reports is the list of all misbehavior reports at genesis.
	Reports []MisbehaviorReport `protobuf:"bytes,4,rep,name=reports,proto3" json:"reports"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f6fd1b6c249558, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetReputationScores() []ReputationScore {
	if m != nil {
		return m.ReputationScores
	}
	return nil
}

func (m *GenesisState) GetFeedbacks() []Feedback {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetReports() []MisbehaviorReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

// Params defines the parameters for the reputation module.
type Params struct {
	// min_rating is the minimum allowed rating value.
	MinRating uint32 `protobuf:"varint,1,opt,name=min_rating,json=minRating,proto3" json:"min_rating,omitempty"`
	// max_rating is the maximum allowed rating value (default 500 = 5.0).
	MaxRating uint32 `protobuf:"varint,2,opt,name=max_rating,json=maxRating,proto3" json:"max_rating,omitempty"`
	// feedback_cooldown_seconds is the minimum time between feedbacks from the same address.
	FeedbackCooldownSeconds uint64 `protobuf:"varint,3,opt,name=feedback_cooldown_seconds,json=feedbackCooldownSeconds,proto3" json:"feedback_cooldown_seconds,omitempty"`
	// verified_weight is the weight multiplier for verified feedbacks.
	VerifiedWeight cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=verified_weight,json=verifiedWeight,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"verified_weight"`
	// unverified_weight is the weight multiplier for unverified feedbacks.
	UnverifiedWeight cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=unverified_weight,json=unverifiedWeight,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"unverified_weight"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f6fd1b6c249558, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinRating() uint32 {
	if m != nil {
		return m.MinRating
	}
	return 0
}

func (m *Params) GetMaxRating() uint32 {
	if m != nil {
		return m.MaxRating
	}
	return 0
}

func (m *Params) GetFeedbackCooldownSeconds() uint64 {
	if m != nil {
		return m.FeedbackCooldownSeconds
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "oasyce.reputation.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "oasyce.reputation.v1.Params")
}

func init() {
	proto.RegisterFile("oasyce/reputation/v1/genesis.proto", fileDescriptor_32f6fd1b6c249558)
}

var fileDescriptor_32f6fd1b6c249558 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x93, 0x2e, 0x14, 0xd5, 0xe3, 0xcf, 0x16, 0x4d, 0x22, 0x1b, 0x90, 0x46, 0x95, 0x10,
	0x15, 0x12, 0x89, 0x3a, 0x6e, 0x3d, 0x96, 0x8a, 0x5d, 0x40, 0x42, 0xe9, 0x01, 0xb4, 0x03, 0x91,
	0xeb, 0xbc, 0x4b, 0xac, 0x91, 0x38, 0xb2, 0xdd, 0xae, 0xfd, 0x16, 0x1c, 0x39, 0xf2, 0x15, 0x90,
	0xf8, 0x08, 0x1c, 0x76, 0x9c, 0x38, 0x21, 0x0e, 0x13, 0x6a, 0xbf, 0x08, 0xaa, 0xed, 0x50, 0x40,
	0x39, 0x71, 0xb3, 0xdf, 0xe7, 0x79, 0x7e, 0xaf, 0x2d, 0x3d, 0xa8, 0xc7, 0xb0, 0x58, 0x12, 0x88,
	0x38, 0x54, 0x33, 0x89, 0x25, 0x65, 0x65, 0x34, 0x1f, 0x44, 0x19, 0x94, 0x20, 0xa8, 0x08, 0x2b,
	0xce, 0x24, 0x73, 0x0f, 0xb4, 0x27, 0xdc, 0x7a, 0xc2, 0xf9, 0xe0, 0xe8, 0x90, 0x30, 0x51, 0x30,
	0x91, 0x28, 0x4f, 0xa4, 0x2f, 0x3a, 0x70, 0x74, 0x90, 0xb1, 0x8c, 0xe9, 0xf9, 0xe6, 0x64, 0xa6,
	0x41, 0xe3, 0x2a, 0xb9, 0xac, 0xc0, 0xe4, 0x7a, 0x9f, 0x5b, 0xe8, 0xd6, 0x89, 0x5e, 0x3d, 0x91,
	0x58, 0x82, 0xfb, 0x16, 0xed, 0x6f, 0xdd, 0x89, 0x20, 0x8c, 0x83, 0xf0, 0xec, 0x60, 0xa7, 0xbf,
	0x7b, 0xfc, 0x28, 0x6c, 0x7a, 0x55, 0x18, 0xff, 0xbe, 0x4d, 0x36, 0xee, 0x91, 0x73, 0x79, 0xdd,
	0xb5, 0xe2, 0x3d, 0xfe, 0xf7, 0x58, 0xb8, 0x23, 0xd4, 0x39, 0x03, 0x48, 0xa7, 0x98, 0x9c, 0x0b,
	0xaf, 0xa5, 0x88, 0x7e, 0x33, 0xf1, 0x85, 0xb1, 0x19, 0xd4, 0x36, 0xe6, 0x0e, 0x51, 0xbb, 0xc2,
	0x1c, 0x17, 0xc2, 0xdb, 0x09, 0xec, 0xfe, 0xee, 0xf1, 0x83, 0x66, 0xc0, 0x6b, 0xe5, 0x31, 0x71,
	0x93, 0x70, 0x4f, 0xd0, 0x4d, 0x0e, 0x15, 0xe3, 0x52, 0x78, 0x8e, 0xda, 0xfe, 0xb8, 0x39, 0xfc,
	0x8a, 0x8a, 0x29, 0xe4, 0x78, 0x4e, 0x19, 0x8f, 0x95, 0xdf, 0x70, 0xea, 0x74, 0xef, 0x6b, 0x0b,
	0xb5, 0xf5, 0x06, 0xf7, 0x21, 0x42, 0x05, 0x2d, 0x13, 0x8e, 0x25, 0x2d, 0x33, 0xcf, 0x0e, 0xec,
	0xfe, 0xed, 0xb8, 0x53, 0xd0, 0x32, 0x56, 0x03, 0x25, 0xe3, 0x45, 0x2d, 0xb7, 0x8c, 0x8c, 0x17,
	0x46, 0x1e, 0xa2, 0xc3, 0xfa, 0x6b, 0x09, 0x61, 0xec, 0x7d, 0xca, 0x2e, 0xca, 0x44, 0x00, 0x61,
	0x65, 0xaa, 0x3f, 0xe8, 0xc4, 0xf7, 0x6a, 0xc3, 0x73, 0xa3, 0x4f, 0xb4, 0xec, 0x9e, 0xa2, 0xbb,
	0x73, 0xe0, 0xf4, 0x8c, 0x42, 0x9a, 0x5c, 0x00, 0xcd, 0x72, 0xe9, 0x39, 0x81, 0xdd, 0xef, 0x8c,
	0x06, 0x9b, 0xc7, 0xfe, 0xb8, 0xee, 0xde, 0xd7, 0xfd, 0x10, 0xe9, 0x79, 0x48, 0x59, 0x54, 0x60,
	0x99, 0x87, 0x2f, 0x21, 0xc3, 0x64, 0x39, 0x06, 0xf2, 0xed, 0xcb, 0x53, 0x64, 0xea, 0x33, 0x06,
	0x12, 0xdf, 0xa9, 0x49, 0x6f, 0x14, 0xc8, 0x7d, 0x87, 0xf6, 0x67, 0xe5, 0xbf, 0xf4, 0x1b, 0xff,
	0x4b, 0xdf, 0xdb, 0xb2, 0x34, 0x7f, 0xe8, 0x7c, 0xfc, 0xd4, 0xb5, 0x46, 0xe3, 0xcb, 0x95, 0x6f,
	0x5f, 0xad, 0x7c, 0xfb, 0xe7, 0xca, 0xb7, 0x3f, 0xac, 0x7d, 0xeb, 0x6a, 0xed, 0x5b, 0xdf, 0xd7,
	0xbe, 0x75, 0xfa, 0x24, 0xa3, 0x32, 0x9f, 0x4d, 0x43, 0xc2, 0x8a, 0xc8, 0x34, 0x98, 0xe4, 0x98,
	0x96, 0xd1, 0xe2, 0xcf, 0x26, 0xab, 0x1a, 0x4f, 0xdb, 0xaa, 0xc7, 0xcf, 0x7e, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x2f, 0xb3, 0x41, 0xb5, 0x56, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reports) > 0 {
		for iNdEx := len(m.Reports) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reports[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Feedbacks) > 0 {
		for iNdEx := len(m.Feedbacks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Feedbacks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ReputationScores) > 0 {
		for iNdEx := len(m.ReputationScores) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReputationScores[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.UnverifiedWeight.Size()
		i -= size
		if _, err := m.UnverifiedWeight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.VerifiedWeight.Size()
		i -= size
		if _, err := m.VerifiedWeight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.FeedbackCooldownSeconds != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.FeedbackCooldownSeconds))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxRating != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxRating))
		i--
		dAtA[i] = 0x10
	}
	if m.MinRating != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinRating))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ReputationScores) > 0 {
		for _, e := range m.ReputationScores {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Feedbacks) > 0 {
		for _, e := range m.Feedbacks {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Reports) > 0 {
		for _, e := range m.Reports {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinRating != 0 {
		n += 1 + sovGenesis(uint64(m.MinRating))
	}
	if m.MaxRating != 0 {
		n += 1 + sovGenesis(uint64(m.MaxRating))
	}
	if m.FeedbackCooldownSeconds != 0 {
		n += 1 + sovGenesis(uint64(m.FeedbackCooldownSeconds))
	}
	l = m.VerifiedWeight.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.UnverifiedWeight.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReputationScores", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReputationScores = append(m.ReputationScores, ReputationScore{})
			if err := m.ReputationScores[len(m.ReputationScores)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedbacks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feedbacks = append(m.Feedbacks, Feedback{})
			if err := m.Feedbacks[len(m.Feedbacks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reports = append(m.Reports, MisbehaviorReport{})
			if err := m.Reports[len(m.Reports)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRating", wireType)
			}
			m.MinRating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinRating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRating", wireType)
			}
			m.MaxRating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRating |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedbackCooldownSeconds", wireType)
			}
			m.FeedbackCooldownSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeedbackCooldownSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiedWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VerifiedWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnverifiedWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnverifiedWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
