// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/reputation/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryReputationRequest is the request type for the Query/Reputation RPC.
type QueryReputationRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryReputationRequest) Reset()         { *m = QueryReputationRequest{} }
func (m *QueryReputationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReputationRequest) ProtoMessage()    {}
func (*QueryReputationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c7271d83d7f7aa, []int{0}
}
func (m *QueryReputationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReputationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReputationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReputationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReputationRequest.Merge(m, src)
}
func (m *QueryReputationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReputationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReputationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReputationRequest proto.InternalMessageInfo

func (m *QueryReputationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryReputationResponse is the response type for the Query/Reputation RPC.
type QueryReputationResponse struct {
	Reputation ReputationScore `protobuf:"bytes,1,opt,name=reputation,proto3" json:"reputation"`
}

func (m *QueryReputationResponse) Reset()         { *m = QueryReputationResponse{} }
func (m *QueryReputationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReputationResponse) ProtoMessage()    {}
func (*QueryReputationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c7271d83d7f7aa, []int{1}
}
func (m *QueryReputationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReputationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReputationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReputationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReputationResponse.Merge(m, src)
}
func (m *QueryReputationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReputationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReputationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReputationResponse proto.InternalMessageInfo

func (m *QueryReputationResponse) GetReputation() ReputationScore {
	if m != nil {
		return m.Reputation
	}
	return ReputationScore{}
}

// QueryFeedbackRequest is the request type for the Query/Feedback RPC.
type QueryFeedbackRequest struct {
	InvocationId string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
}

func (m *QueryFeedbackRequest) Reset()         { *m = QueryFeedbackRequest{} }
func (m *QueryFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFeedbackRequest) ProtoMessage()    {}
func (*QueryFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c7271d83d7f7aa, []int{2}
}
func (m *QueryFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFeedbackRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFeedbackRequest.Merge(m, src)
}
func (m *QueryFeedbackRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFeedbackRequest proto.InternalMessageInfo

func (m *QueryFeedbackRequest) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

// QueryFeedbackResponse is the response type for the Query/Feedback RPC.
type QueryFeedbackResponse struct {
	Feedbacks []Feedback `protobuf:"bytes,1,rep,name=feedbacks,proto3" json:"feedbacks"`
}

func (m *QueryFeedbackResponse) Reset()         { *m = QueryFeedbackResponse{} }
func (m *QueryFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFeedbackResponse) ProtoMessage()    {}
func (*QueryFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c7271d83d7f7aa, []int{3}
}
func (m *QueryFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFeedbackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFeedbackResponse.Merge(m, src)
}
func (m *QueryFeedbackResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFeedbackResponse proto.InternalMessageInfo

func (m *QueryFeedbackResponse) GetFeedbacks() []Feedback {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

// QueryLeaderboardRequest is the request type for the Query/Leaderboard RPC.
type QueryLeaderboardRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLeaderboardRequest) Reset()         { *m = QueryLeaderboardRequest{} }
func (m *QueryLeaderboardRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLeaderboardRequest) ProtoMessage()    {}
func (*QueryLeaderboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c7271d83d7f7aa, []int{4}
}
func (m *QueryLeaderboardRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLeaderboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLeaderboardRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLeaderboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLeaderboardRequest.Merge(m, src)
}
func (m *QueryLeaderboardRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLeaderboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLeaderboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLeaderboardRequest proto.InternalMessageInfo

func (m *QueryLeaderboardRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryLeaderboardResponse is the response type for the Query/Leaderboard RPC.
type QueryLeaderboardResponse struct {
	Scores     []ReputationScore   `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryLeaderboardResponse) Reset()         { *m = QueryLeaderboardResponse{} }
func (m *QueryLeaderboardResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLeaderboardResponse) ProtoMessage()    {}
func (*QueryLeaderboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c7271d83d7f7aa, []int{5}
}
func (m *QueryLeaderboardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLeaderboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLeaderboardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLeaderboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLeaderboardResponse.Merge(m, src)
}
func (m *QueryLeaderboardResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLeaderboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLeaderboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLeaderboardResponse proto.InternalMessageInfo

func (m *QueryLeaderboardResponse) GetScores() []ReputationScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *QueryLeaderboardResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryReputationParamsRequest is the request type for the Query/ReputationParams RPC.
type QueryReputationParamsRequest struct {
}

func (m *QueryReputationParamsRequest) Reset()         { *m = QueryReputationParamsRequest{} }
func (m *QueryReputationParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReputationParamsRequest) ProtoMessage()    {}
func (*QueryReputationParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c7271d83d7f7aa, []int{6}
}
func (m *QueryReputationParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReputationParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReputationParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReputationParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReputationParamsRequest.Merge(m, src)
}
func (m *QueryReputationParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReputationParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReputationParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReputationParamsRequest proto.InternalMessageInfo

// QueryReputationParamsResponse is the response type for the Query/ReputationParams RPC.
type QueryReputationParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryReputationParamsResponse) Reset()         { *m = QueryReputationParamsResponse{} }
func (m *QueryReputationParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReputationParamsResponse) ProtoMessage()    {}
func (*QueryReputationParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9c7271d83d7f7aa, []int{7}
}
func (m *QueryReputationParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReputationParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReputationParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReputationParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReputationParamsResponse.Merge(m, src)
}
func (m *QueryReputationParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReputationParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReputationParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReputationParamsResponse proto.InternalMessageInfo

func (m *QueryReputationParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*QueryReputationRequest)(nil), "oasyce.reputation.v1.QueryReputationRequest")
	proto.RegisterType((*QueryReputationResponse)(nil), "oasyce.reputation.v1.QueryReputationResponse")
	proto.RegisterType((*QueryFeedbackRequest)(nil), "oasyce.reputation.v1.QueryFeedbackRequest")
	proto.RegisterType((*QueryFeedbackResponse)(nil), "oasyce.reputation.v1.QueryFeedbackResponse")
	proto.RegisterType((*QueryLeaderboardRequest)(nil), "oasyce.reputation.v1.QueryLeaderboardRequest")
	proto.RegisterType((*QueryLeaderboardResponse)(nil), "oasyce.reputation.v1.QueryLeaderboardResponse")
	proto.RegisterType((*QueryReputationParamsRequest)(nil), "oasyce.reputation.v1.QueryReputationParamsRequest")
	proto.RegisterType((*QueryReputationParamsResponse)(nil), "oasyce.reputation.v1.QueryReputationParamsResponse")
}

func init() { proto.RegisterFile("oasyce/reputation/v1/query.proto", fileDescriptor_d9c7271d83d7f7aa) }

var fileDescriptor_d9c7271d83d7f7aa = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0xe3, 0x42, 0x0b, 0x7d, 0x0b, 0x12, 0x3a, 0x05, 0x88, 0xac, 0x60, 0x8a, 0xcb, 0x9f,
	0x12, 0xca, 0x1d, 0x71, 0x25, 0x06, 0xd8, 0x02, 0x2a, 0x42, 0x30, 0x94, 0xb0, 0xd1, 0x01, 0x9d,
	0xed, 0xab, 0x6b, 0xd1, 0xf8, 0x5c, 0x9f, 0x13, 0x11, 0x55, 0x5d, 0xe0, 0x0b, 0x20, 0x31, 0x30,
	0x20, 0x06, 0x36, 0x3e, 0x4a, 0xc7, 0x4a, 0x2c, 0x4c, 0x08, 0x25, 0x7c, 0x10, 0x94, 0xf3, 0x19,
	0x3b, 0xc9, 0x51, 0xd2, 0xcd, 0x3e, 0x3f, 0xcf, 0xfb, 0xfe, 0xde, 0xd7, 0x8f, 0x0d, 0xcb, 0x9c,
	0x8a, 0xbe, 0xc7, 0x48, 0xc2, 0xe2, 0x6e, 0x4a, 0xd3, 0x90, 0x47, 0xa4, 0xd7, 0x24, 0x7b, 0x5d,
	0x96, 0xf4, 0x71, 0x9c, 0xf0, 0x94, 0xa3, 0x6a, 0xa6, 0xc0, 0x85, 0x02, 0xf7, 0x9a, 0x66, 0xc3,
	0xe3, 0xa2, 0xc3, 0x05, 0x71, 0xa9, 0x60, 0x99, 0x9c, 0xf4, 0x9a, 0x2e, 0x4b, 0x69, 0x93, 0xc4,
	0x34, 0x08, 0xa3, 0x4c, 0x28, 0x2b, 0x98, 0xd5, 0x80, 0x07, 0x5c, 0x5e, 0x92, 0xd1, 0x95, 0x3a,
	0xad, 0x07, 0x9c, 0x07, 0xbb, 0x8c, 0xd0, 0x38, 0x24, 0x34, 0x8a, 0x78, 0x56, 0x5b, 0xa8, 0xa7,
	0x7a, 0xae, 0xb4, 0x1f, 0xb3, 0x5c, 0x61, 0x6b, 0x15, 0x01, 0x8b, 0x98, 0x08, 0x95, 0xc6, 0x76,
	0xe0, 0xd2, 0x8b, 0x11, 0x5b, 0xfb, 0xaf, 0xa6, 0xcd, 0xf6, 0xba, 0x4c, 0xa4, 0xa8, 0x06, 0x67,
	0xa8, 0xef, 0x27, 0x4c, 0x88, 0x9a, 0xb1, 0x6c, 0xac, 0x2e, 0xb6, 0xf3, 0x5b, 0x7b, 0x1b, 0x2e,
	0x4f, 0x79, 0x44, 0xcc, 0x23, 0xc1, 0xd0, 0x33, 0x80, 0xa2, 0x9b, 0xf4, 0x2d, 0x39, 0x37, 0xb0,
	0x6e, 0x3f, 0xb8, 0x70, 0xbf, 0xf4, 0x78, 0xc2, 0x5a, 0xa7, 0x0f, 0x7f, 0x5e, 0xad, 0xb4, 0x4b,
	0x76, 0xfb, 0x21, 0x54, 0x65, 0x9f, 0x0d, 0xc6, 0x7c, 0x97, 0x7a, 0x6f, 0x72, 0xb2, 0x15, 0x38,
	0x1f, 0x46, 0x3d, 0xee, 0x49, 0xd5, 0xeb, 0xd0, 0x57, 0x7c, 0xe7, 0x8a, 0xc3, 0xa7, 0xbe, 0xbd,
	0x05, 0x17, 0x27, 0xcc, 0x0a, 0xb1, 0x05, 0x8b, 0xdb, 0xea, 0x6c, 0x34, 0xd9, 0xa9, 0xd5, 0x25,
	0xc7, 0xd2, 0x13, 0xe6, 0x56, 0x85, 0x56, 0xd8, 0x6c, 0xaa, 0x36, 0xf0, 0x9c, 0x51, 0x9f, 0x25,
	0x2e, 0xa7, 0x89, 0x9f, 0xc3, 0x6d, 0x00, 0x14, 0xaf, 0x57, 0x6d, 0xe0, 0x26, 0xce, 0xb2, 0x80,
	0x47, 0x59, 0xc0, 0x59, 0x74, 0x54, 0x16, 0xf0, 0x26, 0x0d, 0x98, 0xf2, 0xb6, 0x4b, 0x4e, 0xfb,
	0x9b, 0x01, 0xb5, 0xe9, 0x1e, 0x6a, 0x86, 0x47, 0xb0, 0x20, 0x46, 0x4b, 0xcb, 0x07, 0x38, 0xd1,
	0x8a, 0x95, 0x15, 0x3d, 0x19, 0x23, 0x9d, 0x93, 0xa4, 0xb7, 0xfe, 0x4b, 0x9a, 0x11, 0x8c, 0xa1,
	0x5a, 0x50, 0x9f, 0xc8, 0xc3, 0x26, 0x4d, 0x68, 0x47, 0xa8, 0xb1, 0xec, 0x2d, 0xb8, 0xf2, 0x8f,
	0xe7, 0x6a, 0x9c, 0x07, 0xb0, 0x10, 0xcb, 0x13, 0xb5, 0xaf, 0xba, 0x7e, 0x9c, 0xcc, 0x95, 0x4f,
	0x91, 0x39, 0x9c, 0xf7, 0xf3, 0x30, 0x2f, 0xab, 0xa3, 0x2f, 0x06, 0x40, 0xd1, 0x02, 0xad, 0xe9,
	0x8b, 0xe8, 0xd3, 0x6e, 0xde, 0x9d, 0x51, 0x9d, 0x11, 0xdb, 0xce, 0xbb, 0xef, 0xbf, 0x3f, 0xce,
	0xad, 0xa1, 0x06, 0xd1, 0x7e, 0x63, 0xa5, 0xbb, 0x7d, 0xf5, 0xd5, 0x1c, 0xa0, 0xcf, 0x06, 0x9c,
	0xcd, 0x23, 0x85, 0x1a, 0xc7, 0xf4, 0x9b, 0xc8, 0xbb, 0x79, 0x67, 0x26, 0xad, 0x22, 0xbb, 0x2f,
	0xc9, 0xee, 0x21, 0xac, 0x27, 0xcb, 0x33, 0x4c, 0xf6, 0xc7, 0x3e, 0xa1, 0x03, 0xf4, 0xc9, 0x80,
	0xa5, 0x52, 0xd4, 0xd0, 0x71, 0x0b, 0x99, 0x8e, 0xbd, 0x89, 0x67, 0x95, 0x2b, 0xcc, 0xdb, 0x12,
	0x73, 0x05, 0x5d, 0xd3, 0x63, 0xee, 0x96, 0x48, 0xbe, 0x1a, 0x70, 0x61, 0x32, 0x3a, 0xc8, 0x99,
	0xe9, 0x7d, 0x8d, 0xe5, 0xd0, 0x5c, 0x3f, 0x91, 0x47, 0x81, 0x5e, 0x97, 0xa0, 0x16, 0xaa, 0xeb,
	0x41, 0xb3, 0x14, 0xb6, 0x1e, 0x1f, 0x0e, 0x2c, 0xe3, 0x68, 0x60, 0x19, 0xbf, 0x06, 0x96, 0xf1,
	0x61, 0x68, 0x55, 0x8e, 0x86, 0x56, 0xe5, 0xc7, 0xd0, 0xaa, 0xbc, 0x6a, 0x04, 0x61, 0xba, 0xd3,
	0x75, 0xb1, 0xc7, 0x3b, 0x79, 0x05, 0x6f, 0x87, 0x86, 0x11, 0x79, 0x5b, 0xae, 0x24, 0x7f, 0xdb,
	0xee, 0x82, 0xfc, 0x27, 0xaf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xf2, 0x87, 0x54, 0x73,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Reputation queries the reputation score of an address.
	Reputation(ctx context.Context, in *QueryReputationRequest, opts ...grpc.CallOption) (*QueryReputationResponse, error)
	// Feedback queries the feedback for a given invocation.
	Feedback(ctx context.Context, in *QueryFeedbackRequest, opts ...grpc.CallOption) (*QueryFeedbackResponse, error)
	// Leaderboard queries the top-rated providers.
	Leaderboard(ctx context.Context, in *QueryLeaderboardRequest, opts ...grpc.CallOption) (*QueryLeaderboardResponse, error)
	// ReputationParams queries the module parameters.
	ReputationParams(ctx context.Context, in *QueryReputationParamsRequest, opts ...grpc.CallOption) (*QueryReputationParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Reputation(ctx context.Context, in *QueryReputationRequest, opts ...grpc.CallOption) (*QueryReputationResponse, error) {
	out := new(QueryReputationResponse)
	err := c.cc.Invoke(ctx, "/oasyce.reputation.v1.Query/Reputation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Feedback(ctx context.Context, in *QueryFeedbackRequest, opts ...grpc.CallOption) (*QueryFeedbackResponse, error) {
	out := new(QueryFeedbackResponse)
	err := c.cc.Invoke(ctx, "/oasyce.reputation.v1.Query/Feedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Leaderboard(ctx context.Context, in *QueryLeaderboardRequest, opts ...grpc.CallOption) (*QueryLeaderboardResponse, error) {
	out := new(QueryLeaderboardResponse)
	err := c.cc.Invoke(ctx, "/oasyce.reputation.v1.Query/Leaderboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReputationParams(ctx context.Context, in *QueryReputationParamsRequest, opts ...grpc.CallOption) (*QueryReputationParamsResponse, error) {
	out := new(QueryReputationParamsResponse)
	err := c.cc.Invoke(ctx, "/oasyce.reputation.v1.Query/ReputationParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Reputation queries the reputation score of an address.
	Reputation(context.Context, *QueryReputationRequest) (*QueryReputationResponse, error)
	// Feedback queries the feedback for a given invocation.
	Feedback(context.Context, *QueryFeedbackRequest) (*QueryFeedbackResponse, error)
	// Leaderboard queries the top-rated providers.
	Leaderboard(context.Context, *QueryLeaderboardRequest) (*QueryLeaderboardResponse, error)
	// ReputationParams queries the module parameters.
	ReputationParams(context.Context, *QueryReputationParamsRequest) (*QueryReputationParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Reputation(ctx context.Context, req *QueryReputationRequest) (*QueryReputationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reputation not implemented")
}
func (*UnimplementedQueryServer) Feedback(ctx context.Context, req *QueryFeedbackRequest) (*QueryFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Feedback not implemented")
}
func (*UnimplementedQueryServer) Leaderboard(ctx context.Context, req *QueryLeaderboardRequest) (*QueryLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leaderboard not implemented")
}
func (*UnimplementedQueryServer) ReputationParams(ctx context.Context, req *QueryReputationParamsRequest) (*QueryReputationParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReputationParams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Reputation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReputationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Reputation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.reputation.v1.Query/Reputation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Reputation(ctx, req.(*QueryReputationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Feedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Feedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.reputation.v1.Query/Feedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Feedback(ctx, req.(*QueryFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Leaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Leaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.reputation.v1.Query/Leaderboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Leaderboard(ctx, req.(*QueryLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReputationParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReputationParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReputationParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.reputation.v1.Query/ReputationParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReputationParams(ctx, req.(*QueryReputationParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oasyce.reputation.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reputation",
			Handler:    _Query_Reputation_Handler,
		},
		{
			MethodName: "Feedback",
			Handler:    _Query_Feedback_Handler,
		},
		{
			MethodName: "Leaderboard",
			Handler:    _Query_Leaderboard_Handler,
		},
		{
			MethodName: "ReputationParams",
			Handler:    _Query_ReputationParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oasyce/reputation/v1/query.proto",
}

func (m *QueryReputationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReputationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReputationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReputationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReputationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReputationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Reputation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryFeedbackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFeedbackRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFeedbackRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InvocationId) > 0 {
		i -= len(m.InvocationId)
		copy(dAtA[i:], m.InvocationId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.InvocationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFeedbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFeedbackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFeedbackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Feedbacks) > 0 {
		for iNdEx := len(m.Feedbacks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Feedbacks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLeaderboardRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLeaderboardRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLeaderboardRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryLeaderboardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLeaderboardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLeaderboardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Scores) > 0 {
		for iNdEx := len(m.Scores) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Scores[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryReputationParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReputationParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReputationParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryReputationParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReputationParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReputationParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryReputationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReputationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Reputation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryFeedbackRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InvocationId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFeedbackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Feedbacks) > 0 {
		for _, e := range m.Feedbacks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryLeaderboardRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryLeaderboardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Scores) > 0 {
		for _, e := range m.Scores {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReputationParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryReputationParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryReputationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReputationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReputationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReputationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReputationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReputationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reputation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reputation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFeedbackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFeedbackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFeedbackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvocationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvocationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFeedbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFeedbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFeedbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedbacks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feedbacks = append(m.Feedbacks, Feedback{})
			if err := m.Feedbacks[len(m.Feedbacks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLeaderboardRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLeaderboardRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLeaderboardRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLeaderboardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLeaderboardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLeaderboardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scores", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scores = append(m.Scores, ReputationScore{})
			if err := m.Scores[len(m.Scores)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReputationParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReputationParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReputationParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReputationParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReputationParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReputationParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
