// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/capability/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryCapabilityRequest is the request type for the Query/Capability RPC.
type QueryCapabilityRequest struct {
	CapabilityId string `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
}

func (m *QueryCapabilityRequest) Reset()         { *m = QueryCapabilityRequest{} }
func (m *QueryCapabilityRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCapabilityRequest) ProtoMessage()    {}
func (*QueryCapabilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{0}
}
func (m *QueryCapabilityRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCapabilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCapabilityRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCapabilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCapabilityRequest.Merge(m, src)
}
func (m *QueryCapabilityRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCapabilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCapabilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCapabilityRequest proto.InternalMessageInfo

func (m *QueryCapabilityRequest) GetCapabilityId() string {
	if m != nil {
		return m.CapabilityId
	}
	return ""
}

// QueryCapabilityResponse is the response type for the Query/Capability RPC.
type QueryCapabilityResponse struct {
	Capability Capability `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability"`
}

func (m *QueryCapabilityResponse) Reset()         { *m = QueryCapabilityResponse{} }
func (m *QueryCapabilityResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCapabilityResponse) ProtoMessage()    {}
func (*QueryCapabilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{1}
}
func (m *QueryCapabilityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCapabilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCapabilityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCapabilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCapabilityResponse.Merge(m, src)
}
func (m *QueryCapabilityResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCapabilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCapabilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCapabilityResponse proto.InternalMessageInfo

func (m *QueryCapabilityResponse) GetCapability() Capability {
	if m != nil {
		return m.Capability
	}
	return Capability{}
}

// QueryCapabilitiesRequest is the request type for the Query/Capabilities RPC.
type QueryCapabilitiesRequest struct {
	// tag filters capabilities by tag. Empty returns all.
	Tag        string             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCapabilitiesRequest) Reset()         { *m = QueryCapabilitiesRequest{} }
func (m *QueryCapabilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCapabilitiesRequest) ProtoMessage()    {}
func (*QueryCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{2}
}
func (m *QueryCapabilitiesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCapabilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCapabilitiesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCapabilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCapabilitiesRequest.Merge(m, src)
}
func (m *QueryCapabilitiesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCapabilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCapabilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCapabilitiesRequest proto.InternalMessageInfo

func (m *QueryCapabilitiesRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *QueryCapabilitiesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryCapabilitiesResponse is the response type for the Query/Capabilities RPC.
type QueryCapabilitiesResponse struct {
	Capabilities []Capability        `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCapabilitiesResponse) Reset()         { *m = QueryCapabilitiesResponse{} }
func (m *QueryCapabilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCapabilitiesResponse) ProtoMessage()    {}
func (*QueryCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{3}
}
func (m *QueryCapabilitiesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCapabilitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCapabilitiesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCapabilitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCapabilitiesResponse.Merge(m, src)
}
func (m *QueryCapabilitiesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCapabilitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCapabilitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCapabilitiesResponse proto.InternalMessageInfo

func (m *QueryCapabilitiesResponse) GetCapabilities() []Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *QueryCapabilitiesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryCapabilitiesByProviderRequest is the request type for Query/CapabilitiesByProvider.
type QueryCapabilitiesByProviderRequest struct {
	Provider   string             `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCapabilitiesByProviderRequest) Reset()         { *m = QueryCapabilitiesByProviderRequest{} }
func (m *QueryCapabilitiesByProviderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCapabilitiesByProviderRequest) ProtoMessage()    {}
func (*QueryCapabilitiesByProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{4}
}
func (m *QueryCapabilitiesByProviderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCapabilitiesByProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCapabilitiesByProviderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCapabilitiesByProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCapabilitiesByProviderRequest.Merge(m, src)
}
func (m *QueryCapabilitiesByProviderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCapabilitiesByProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCapabilitiesByProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCapabilitiesByProviderRequest proto.InternalMessageInfo

func (m *QueryCapabilitiesByProviderRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *QueryCapabilitiesByProviderRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryCapabilitiesByProviderResponse is the response type for Query/CapabilitiesByProvider.
type QueryCapabilitiesByProviderResponse struct {
	Capabilities []Capability        `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCapabilitiesByProviderResponse) Reset()         { *m = QueryCapabilitiesByProviderResponse{} }
func (m *QueryCapabilitiesByProviderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCapabilitiesByProviderResponse) ProtoMessage()    {}
func (*QueryCapabilitiesByProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{5}
}
func (m *QueryCapabilitiesByProviderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCapabilitiesByProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCapabilitiesByProviderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCapabilitiesByProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCapabilitiesByProviderResponse.Merge(m, src)
}
func (m *QueryCapabilitiesByProviderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCapabilitiesByProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCapabilitiesByProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCapabilitiesByProviderResponse proto.InternalMessageInfo

func (m *QueryCapabilitiesByProviderResponse) GetCapabilities() []Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *QueryCapabilitiesByProviderResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryEarningsRequest is the request type for the Query/Earnings RPC.
type QueryEarningsRequest struct {
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (m *QueryEarningsRequest) Reset()         { *m = QueryEarningsRequest{} }
func (m *QueryEarningsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEarningsRequest) ProtoMessage()    {}
func (*QueryEarningsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{6}
}
func (m *QueryEarningsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEarningsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEarningsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEarningsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEarningsRequest.Merge(m, src)
}
func (m *QueryEarningsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEarningsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEarningsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEarningsRequest proto.InternalMessageInfo

func (m *QueryEarningsRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

// QueryEarningsResponse is the response type for the Query/Earnings RPC.
type QueryEarningsResponse struct {
	// total_earned is the total amount earned across all capabilities.
	TotalEarned []types.Coin `protobuf:"bytes,1,rep,name=total_earned,json=totalEarned,proto3" json:"total_earned"`
	// total_calls is the total number of successful invocations.
	TotalCalls uint64 `protobuf:"varint,2,opt,name=total_calls,json=totalCalls,proto3" json:"total_calls,omitempty"`
}

func (m *QueryEarningsResponse) Reset()         { *m = QueryEarningsResponse{} }
func (m *QueryEarningsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEarningsResponse) ProtoMessage()    {}
func (*QueryEarningsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{7}
}
func (m *QueryEarningsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEarningsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEarningsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEarningsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEarningsResponse.Merge(m, src)
}
func (m *QueryEarningsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEarningsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEarningsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEarningsResponse proto.InternalMessageInfo

func (m *QueryEarningsResponse) GetTotalEarned() []types.Coin {
	if m != nil {
		return m.TotalEarned
	}
	return nil
}

func (m *QueryEarningsResponse) GetTotalCalls() uint64 {
	if m != nil {
		return m.TotalCalls
	}
	return 0
}

// QueryInvocationRequest is the request type for the Query/Invocation RPC.
type QueryInvocationRequest struct {
	InvocationId string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
}

func (m *QueryInvocationRequest) Reset()         { *m = QueryInvocationRequest{} }
func (m *QueryInvocationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInvocationRequest) ProtoMessage()    {}
func (*QueryInvocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{8}
}
func (m *QueryInvocationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInvocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInvocationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInvocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInvocationRequest.Merge(m, src)
}
func (m *QueryInvocationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInvocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInvocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInvocationRequest proto.InternalMessageInfo

func (m *QueryInvocationRequest) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

// QueryInvocationResponse is the response type for the Query/Invocation RPC.
type QueryInvocationResponse struct {
	Invocation Invocation `protobuf:"bytes,1,opt,name=invocation,proto3" json:"invocation"`
}

func (m *QueryInvocationResponse) Reset()         { *m = QueryInvocationResponse{} }
func (m *QueryInvocationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInvocationResponse) ProtoMessage()    {}
func (*QueryInvocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76eec79927870477, []int{9}
}
func (m *QueryInvocationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInvocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInvocationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInvocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInvocationResponse.Merge(m, src)
}
func (m *QueryInvocationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInvocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInvocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInvocationResponse proto.InternalMessageInfo

func (m *QueryInvocationResponse) GetInvocation() Invocation {
	if m != nil {
		return m.Invocation
	}
	return Invocation{}
}

func init() {
	proto.RegisterType((*QueryCapabilityRequest)(nil), "oasyce.capability.v1.QueryCapabilityRequest")
	proto.RegisterType((*QueryCapabilityResponse)(nil), "oasyce.capability.v1.QueryCapabilityResponse")
	proto.RegisterType((*QueryCapabilitiesRequest)(nil), "oasyce.capability.v1.QueryCapabilitiesRequest")
	proto.RegisterType((*QueryCapabilitiesResponse)(nil), "oasyce.capability.v1.QueryCapabilitiesResponse")
	proto.RegisterType((*QueryCapabilitiesByProviderRequest)(nil), "oasyce.capability.v1.QueryCapabilitiesByProviderRequest")
	proto.RegisterType((*QueryCapabilitiesByProviderResponse)(nil), "oasyce.capability.v1.QueryCapabilitiesByProviderResponse")
	proto.RegisterType((*QueryEarningsRequest)(nil), "oasyce.capability.v1.QueryEarningsRequest")
	proto.RegisterType((*QueryEarningsResponse)(nil), "oasyce.capability.v1.QueryEarningsResponse")
	proto.RegisterType((*QueryInvocationRequest)(nil), "oasyce.capability.v1.QueryInvocationRequest")
	proto.RegisterType((*QueryInvocationResponse)(nil), "oasyce.capability.v1.QueryInvocationResponse")
}

func init() { proto.RegisterFile("oasyce/capability/v1/query.proto", fileDescriptor_76eec79927870477) }

var fileDescriptor_76eec79927870477 = []byte{
	// 690 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0x4f, 0x6b, 0xd4, 0x4e,
	0x18, 0xc7, 0x77, 0xda, 0xfe, 0x4a, 0x7f, 0x4f, 0x2b, 0xc8, 0x50, 0xeb, 0x36, 0x48, 0xba, 0xa4,
	0xe2, 0x9f, 0xad, 0x66, 0xdc, 0x15, 0xa4, 0x1e, 0x14, 0xd9, 0x5a, 0xa5, 0x9e, 0xea, 0x1e, 0xf5,
	0x50, 0x66, 0xb3, 0x43, 0x3a, 0xb0, 0xcd, 0xa4, 0x9b, 0x74, 0x71, 0xa9, 0xbd, 0x78, 0xf2, 0x28,
	0x08, 0x5e, 0x3c, 0x78, 0xf0, 0x0d, 0x78, 0xf6, 0x15, 0xf4, 0x22, 0x14, 0xbc, 0x78, 0x12, 0x69,
	0x7d, 0x21, 0x92, 0xc9, 0x64, 0x67, 0xb6, 0x1b, 0xb6, 0x51, 0x3c, 0x78, 0x9b, 0x3c, 0xf9, 0x7e,
	0xe7, 0xf9, 0x3c, 0x4f, 0xe6, 0x99, 0x40, 0x45, 0xd0, 0xa8, 0xef, 0x31, 0xe2, 0xd1, 0x90, 0xb6,
	0x78, 0x87, 0xc7, 0x7d, 0xd2, 0xab, 0x91, 0xdd, 0x3d, 0xd6, 0xed, 0xbb, 0x61, 0x57, 0xc4, 0x02,
	0xcf, 0xa7, 0x0a, 0x57, 0x2b, 0xdc, 0x5e, 0xcd, 0xb2, 0x3d, 0x11, 0xed, 0x88, 0x88, 0xb4, 0x68,
	0xc4, 0x48, 0xaf, 0xd6, 0x62, 0x31, 0xad, 0x11, 0x4f, 0xf0, 0x20, 0x75, 0x59, 0x55, 0xf3, 0xbd,
	0xdc, 0x6e, 0xa0, 0x0a, 0xa9, 0xcf, 0x03, 0x1a, 0x73, 0x91, 0x69, 0xe7, 0x7d, 0xe1, 0x0b, 0xb9,
	0x24, 0xc9, 0x4a, 0x45, 0x2f, 0xf9, 0x42, 0xf8, 0x1d, 0x46, 0x68, 0xc8, 0x09, 0x0d, 0x02, 0x11,
	0x4b, 0x4b, 0xa4, 0xde, 0xe6, 0x73, 0xc7, 0xfd, 0x90, 0x29, 0x85, 0x73, 0x0f, 0x16, 0x9e, 0x26,
	0x79, 0xd7, 0x06, 0x8a, 0x26, 0xdb, 0xdd, 0x63, 0x51, 0x8c, 0x97, 0xe1, 0x9c, 0xb6, 0x6d, 0xf1,
	0x76, 0x19, 0x55, 0xd0, 0xb5, 0xff, 0x9b, 0x73, 0x3a, 0xb8, 0xd1, 0x76, 0x28, 0x5c, 0x1c, 0xb1,
	0x47, 0xa1, 0x08, 0x22, 0x86, 0x1f, 0x01, 0x68, 0xa9, 0x34, 0xcf, 0xd6, 0x2b, 0x6e, 0x5e, 0x9b,
	0x5c, 0xed, 0x6e, 0x4c, 0x1d, 0x7e, 0x5f, 0x2a, 0x35, 0x0d, 0xa7, 0x13, 0x43, 0x79, 0x38, 0x05,
	0x67, 0x51, 0xc6, 0x78, 0x1e, 0x26, 0x63, 0xea, 0x2b, 0xb2, 0x64, 0x99, 0x64, 0xd5, 0x9d, 0x2b,
	0x4f, 0xc8, 0xac, 0x57, 0xdc, 0xb4, 0xcd, 0x6e, 0xd2, 0x66, 0x37, 0xfd, 0x6a, 0xaa, 0xcd, 0xee,
	0x26, 0xf5, 0x99, 0xda, 0xad, 0x69, 0x38, 0x9d, 0x4f, 0x08, 0x16, 0x73, 0xd2, 0xaa, 0xda, 0x9e,
	0x80, 0x6e, 0x03, 0x67, 0x51, 0x19, 0x55, 0x26, 0x7f, 0xa3, 0xba, 0x21, 0x2f, 0x7e, 0x9c, 0x43,
	0x7c, 0xf5, 0x4c, 0xe2, 0x14, 0x64, 0x08, 0xf9, 0x35, 0x02, 0x67, 0x04, 0xb9, 0xd1, 0xdf, 0xec,
	0x8a, 0x1e, 0x6f, 0xb3, 0x6e, 0xd6, 0x33, 0x0b, 0x66, 0x42, 0x15, 0x52, 0x8d, 0x1b, 0x3c, 0xff,
	0xb5, 0xee, 0x7d, 0x46, 0xb0, 0x3c, 0x16, 0xe5, 0x5f, 0xee, 0x63, 0x1d, 0xe6, 0x25, 0xfb, 0x3a,
	0xed, 0x06, 0x3c, 0xf0, 0xa3, 0x02, 0x8d, 0x73, 0x5e, 0xc2, 0x85, 0x53, 0x1e, 0x55, 0x61, 0x03,
	0xe6, 0x62, 0x11, 0xd3, 0xce, 0x16, 0xa3, 0xdd, 0x80, 0xb5, 0x55, 0x85, 0x8b, 0x43, 0x5c, 0x19,
	0xd1, 0x9a, 0xe0, 0x81, 0x2a, 0x6d, 0x56, 0x9a, 0xd6, 0xa5, 0x07, 0x2f, 0x41, 0xfa, 0xb8, 0xe5,
	0xd1, 0x4e, 0x27, 0x92, 0xa5, 0x4d, 0x35, 0x41, 0x86, 0xd6, 0x92, 0xc8, 0x60, 0x88, 0x37, 0x82,
	0x9e, 0xf0, 0x64, 0x11, 0xc6, 0x10, 0xf3, 0x41, 0xd0, 0x18, 0x62, 0x1d, 0xdc, 0x68, 0x3b, 0xcf,
	0xd5, 0x10, 0x9b, 0x76, 0x85, 0xff, 0x00, 0x40, 0x4b, 0xc7, 0x0f, 0xb1, 0xe1, 0x36, 0x3c, 0xf5,
	0x0f, 0xd3, 0xf0, 0x9f, 0xdc, 0x1d, 0x7f, 0x44, 0x00, 0xfa, 0x1b, 0xe2, 0x1b, 0xf9, 0xdb, 0xe4,
	0xdf, 0x46, 0xd6, 0xcd, 0x82, 0xea, 0x94, 0xdb, 0x59, 0x7d, 0xf5, 0xf5, 0xe7, 0xdb, 0x89, 0x3a,
	0xbe, 0x45, 0x72, 0x6f, 0x40, 0xe3, 0x69, 0x7f, 0xe8, 0x92, 0x3b, 0xc0, 0xef, 0x11, 0xcc, 0x99,
	0xa7, 0x16, 0xbb, 0x45, 0x32, 0xeb, 0x3b, 0xc9, 0x22, 0x85, 0xf5, 0x8a, 0xb5, 0x2a, 0x59, 0x2f,
	0x63, 0xe7, 0x0c, 0xd6, 0x04, 0xe6, 0x0b, 0x82, 0x85, 0xfc, 0x99, 0xc2, 0xab, 0x05, 0xf3, 0x8e,
	0xdc, 0x08, 0xd6, 0xdd, 0x3f, 0x70, 0x2a, 0xf6, 0xfb, 0x92, 0x7d, 0x15, 0xdf, 0x39, 0x9b, 0x9d,
	0x64, 0xc3, 0x42, 0xf6, 0xb3, 0xd5, 0x01, 0x7e, 0x87, 0x60, 0x26, 0x9b, 0x19, 0x5c, 0x1d, 0xc3,
	0x71, 0x6a, 0x18, 0xad, 0x95, 0x42, 0x5a, 0x45, 0x59, 0x93, 0x94, 0x2b, 0xf8, 0x7a, 0x3e, 0x25,
	0x53, 0x7a, 0x13, 0x8c, 0x03, 0xe8, 0x03, 0x3d, 0xf6, 0xac, 0x8e, 0x0c, 0xdd, 0xd8, 0xb3, 0x3a,
	0x3a, 0x63, 0x8d, 0x87, 0xcf, 0xaa, 0x3e, 0x8f, 0xb7, 0xf7, 0x5a, 0xae, 0x27, 0x76, 0x06, 0x84,
	0xdb, 0x94, 0x07, 0xe4, 0x85, 0x49, 0x2a, 0x7f, 0xdb, 0x87, 0xc7, 0x36, 0x3a, 0x3a, 0xb6, 0xd1,
	0x8f, 0x63, 0x1b, 0xbd, 0x39, 0xb1, 0x4b, 0x47, 0x27, 0x76, 0xe9, 0xdb, 0x89, 0x5d, 0x6a, 0x4d,
	0xcb, 0xff, 0xf9, 0xed, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x47, 0x3f, 0xe4, 0x59, 0xab, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Capability queries a capability by ID.
	Capability(ctx context.Context, in *QueryCapabilityRequest, opts ...grpc.CallOption) (*QueryCapabilityResponse, error)
	// Capabilities queries all capabilities with optional tag filter.
	Capabilities(ctx context.Context, in *QueryCapabilitiesRequest, opts ...grpc.CallOption) (*QueryCapabilitiesResponse, error)
	// CapabilitiesByProvider queries capabilities registered by a provider.
	CapabilitiesByProvider(ctx context.Context, in *QueryCapabilitiesByProviderRequest, opts ...grpc.CallOption) (*QueryCapabilitiesByProviderResponse, error)
	// Earnings queries the total earnings for a provider.
	Earnings(ctx context.Context, in *QueryEarningsRequest, opts ...grpc.CallOption) (*QueryEarningsResponse, error)
	// Invocation queries an invocation by ID.
	Invocation(ctx context.Context, in *QueryInvocationRequest, opts ...grpc.CallOption) (*QueryInvocationResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Capability(ctx context.Context, in *QueryCapabilityRequest, opts ...grpc.CallOption) (*QueryCapabilityResponse, error) {
	out := new(QueryCapabilityResponse)
	err := c.cc.Invoke(ctx, "/oasyce.capability.v1.Query/Capability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Capabilities(ctx context.Context, in *QueryCapabilitiesRequest, opts ...grpc.CallOption) (*QueryCapabilitiesResponse, error) {
	out := new(QueryCapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/oasyce.capability.v1.Query/Capabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CapabilitiesByProvider(ctx context.Context, in *QueryCapabilitiesByProviderRequest, opts ...grpc.CallOption) (*QueryCapabilitiesByProviderResponse, error) {
	out := new(QueryCapabilitiesByProviderResponse)
	err := c.cc.Invoke(ctx, "/oasyce.capability.v1.Query/CapabilitiesByProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Earnings(ctx context.Context, in *QueryEarningsRequest, opts ...grpc.CallOption) (*QueryEarningsResponse, error) {
	out := new(QueryEarningsResponse)
	err := c.cc.Invoke(ctx, "/oasyce.capability.v1.Query/Earnings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Invocation(ctx context.Context, in *QueryInvocationRequest, opts ...grpc.CallOption) (*QueryInvocationResponse, error) {
	out := new(QueryInvocationResponse)
	err := c.cc.Invoke(ctx, "/oasyce.capability.v1.Query/Invocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Capability queries a capability by ID.
	Capability(context.Context, *QueryCapabilityRequest) (*QueryCapabilityResponse, error)
	// Capabilities queries all capabilities with optional tag filter.
	Capabilities(context.Context, *QueryCapabilitiesRequest) (*QueryCapabilitiesResponse, error)
	// CapabilitiesByProvider queries capabilities registered by a provider.
	CapabilitiesByProvider(context.Context, *QueryCapabilitiesByProviderRequest) (*QueryCapabilitiesByProviderResponse, error)
	// Earnings queries the total earnings for a provider.
	Earnings(context.Context, *QueryEarningsRequest) (*QueryEarningsResponse, error)
	// Invocation queries an invocation by ID.
	Invocation(context.Context, *QueryInvocationRequest) (*QueryInvocationResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Capability(ctx context.Context, req *QueryCapabilityRequest) (*QueryCapabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capability not implemented")
}
func (*UnimplementedQueryServer) Capabilities(ctx context.Context, req *QueryCapabilitiesRequest) (*QueryCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (*UnimplementedQueryServer) CapabilitiesByProvider(ctx context.Context, req *QueryCapabilitiesByProviderRequest) (*QueryCapabilitiesByProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CapabilitiesByProvider not implemented")
}
func (*UnimplementedQueryServer) Earnings(ctx context.Context, req *QueryEarningsRequest) (*QueryEarningsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Earnings not implemented")
}
func (*UnimplementedQueryServer) Invocation(ctx context.Context, req *QueryInvocationRequest) (*QueryInvocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invocation not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Capability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCapabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Capability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.capability.v1.Query/Capability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Capability(ctx, req.(*QueryCapabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.capability.v1.Query/Capabilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Capabilities(ctx, req.(*QueryCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CapabilitiesByProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCapabilitiesByProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CapabilitiesByProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.capability.v1.Query/CapabilitiesByProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CapabilitiesByProvider(ctx, req.(*QueryCapabilitiesByProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Earnings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEarningsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Earnings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.capability.v1.Query/Earnings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Earnings(ctx, req.(*QueryEarningsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Invocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInvocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Invocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.capability.v1.Query/Invocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Invocation(ctx, req.(*QueryInvocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oasyce.capability.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capability",
			Handler:    _Query_Capability_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _Query_Capabilities_Handler,
		},
		{
			MethodName: "CapabilitiesByProvider",
			Handler:    _Query_CapabilitiesByProvider_Handler,
		},
		{
			MethodName: "Earnings",
			Handler:    _Query_Earnings_Handler,
		},
		{
			MethodName: "Invocation",
			Handler:    _Query_Invocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oasyce/capability/v1/query.proto",
}

func (m *QueryCapabilityRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCapabilityRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCapabilityRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CapabilityId) > 0 {
		i -= len(m.CapabilityId)
		copy(dAtA[i:], m.CapabilityId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.CapabilityId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCapabilityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCapabilityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCapabilityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Capability.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCapabilitiesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCapabilitiesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCapabilitiesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tag) > 0 {
		i -= len(m.Tag)
		copy(dAtA[i:], m.Tag)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Tag)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCapabilitiesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCapabilitiesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCapabilitiesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Capabilities) > 0 {
		for iNdEx := len(m.Capabilities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Capabilities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryCapabilitiesByProviderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCapabilitiesByProviderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCapabilitiesByProviderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCapabilitiesByProviderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCapabilitiesByProviderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCapabilitiesByProviderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Capabilities) > 0 {
		for iNdEx := len(m.Capabilities) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Capabilities[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEarningsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEarningsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEarningsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEarningsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEarningsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEarningsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalCalls != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalCalls))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TotalEarned) > 0 {
		for iNdEx := len(m.TotalEarned) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalEarned[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryInvocationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInvocationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInvocationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InvocationId) > 0 {
		i -= len(m.InvocationId)
		copy(dAtA[i:], m.InvocationId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.InvocationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInvocationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInvocationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInvocationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Invocation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryCapabilityRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CapabilityId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCapabilityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Capability.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCapabilitiesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tag)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCapabilitiesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Capabilities) > 0 {
		for _, e := range m.Capabilities {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCapabilitiesByProviderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCapabilitiesByProviderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Capabilities) > 0 {
		for _, e := range m.Capabilities {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEarningsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEarningsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TotalEarned) > 0 {
		for _, e := range m.TotalEarned {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.TotalCalls != 0 {
		n += 1 + sovQuery(uint64(m.TotalCalls))
	}
	return n
}

func (m *QueryInvocationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.InvocationId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInvocationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Invocation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryCapabilityRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCapabilityRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCapabilityRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapabilityId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CapabilityId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCapabilityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCapabilityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCapabilityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capability", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Capability.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCapabilitiesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCapabilitiesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCapabilitiesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCapabilitiesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCapabilitiesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCapabilitiesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capabilities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capabilities = append(m.Capabilities, Capability{})
			if err := m.Capabilities[len(m.Capabilities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCapabilitiesByProviderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCapabilitiesByProviderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCapabilitiesByProviderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCapabilitiesByProviderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCapabilitiesByProviderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCapabilitiesByProviderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capabilities", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capabilities = append(m.Capabilities, Capability{})
			if err := m.Capabilities[len(m.Capabilities)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEarningsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEarningsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEarningsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEarningsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEarningsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEarningsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalEarned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalEarned = append(m.TotalEarned, types.Coin{})
			if err := m.TotalEarned[len(m.TotalEarned)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCalls", wireType)
			}
			m.TotalCalls = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCalls |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInvocationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInvocationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInvocationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvocationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvocationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInvocationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInvocationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInvocationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invocation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Invocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
