// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/capability/v1/types.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// InvocationStatus enumerates the possible states of an invocation.
type InvocationStatus int32

const (
	// INVOCATION_STATUS_UNSPECIFIED is the default value.
	INVOCATION_STATUS_UNSPECIFIED InvocationStatus = 0
	// INVOCATION_STATUS_PENDING means the invocation is in progress.
	INVOCATION_STATUS_PENDING InvocationStatus = 1
	// INVOCATION_STATUS_SUCCESS means the invocation completed successfully.
	INVOCATION_STATUS_SUCCESS InvocationStatus = 2
	// INVOCATION_STATUS_FAILED means the invocation failed.
	INVOCATION_STATUS_FAILED InvocationStatus = 3
)

var InvocationStatus_name = map[int32]string{
	0: "INVOCATION_STATUS_UNSPECIFIED",
	1: "INVOCATION_STATUS_PENDING",
	2: "INVOCATION_STATUS_SUCCESS",
	3: "INVOCATION_STATUS_FAILED",
}

var InvocationStatus_value = map[string]int32{
	"INVOCATION_STATUS_UNSPECIFIED": 0,
	"INVOCATION_STATUS_PENDING":     1,
	"INVOCATION_STATUS_SUCCESS":     2,
	"INVOCATION_STATUS_FAILED":      3,
}

func (x InvocationStatus) String() string {
	return proto.EnumName(InvocationStatus_name, int32(x))
}

func (InvocationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_81373fc0ccc58e21, []int{0}
}

// Capability represents a registered AI capability endpoint.
type Capability struct {
	// id is the unique identifier of the capability.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// provider is the address of the capability provider.
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// name is the human-readable name of the capability.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// description is a detailed description of the capability.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// endpoint_url is the encrypted endpoint URL for the capability.
	EndpointUrl string `protobuf:"bytes,5,opt,name=endpoint_url,json=endpointUrl,proto3" json:"endpoint_url,omitempty"`
	// price_per_call is the price charged per invocation.
	PricePerCall types.Coin `protobuf:"bytes,6,opt,name=price_per_call,json=pricePerCall,proto3" json:"price_per_call"`
	// tags are searchable labels for the capability.
	Tags []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// rate_limit is the maximum number of calls allowed per block.
	RateLimit uint64 `protobuf:"varint,8,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	// total_calls is the total number of invocations of this capability.
	TotalCalls uint64 `protobuf:"varint,9,opt,name=total_calls,json=totalCalls,proto3" json:"total_calls,omitempty"`
	// total_earned is the total amount earned by this capability.
	TotalEarned cosmossdk_io_math.Int `protobuf:"bytes,10,opt,name=total_earned,json=totalEarned,proto3,customtype=cosmossdk.io/math.Int" json:"total_earned"`
	// avg_latency_ms is the average invocation latency in milliseconds.
	AvgLatencyMs uint64 `protobuf:"varint,11,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	// success_rate is the success rate in basis points (0-10000 = 0%-100%).
	SuccessRate uint32 `protobuf:"varint,12,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	// is_active indicates whether the capability is currently available.
	IsActive bool `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// created_at is the timestamp when the capability was registered.
	CreatedAt time.Time `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
}

func (m *Capability) Reset()         { *m = Capability{} }
func (m *Capability) String() string { return proto.CompactTextString(m) }
func (*Capability) ProtoMessage()    {}
func (*Capability) Descriptor() ([]byte, []int) {
	return fileDescriptor_81373fc0ccc58e21, []int{0}
}
func (m *Capability) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Capability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Capability.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Capability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capability.Merge(m, src)
}
func (m *Capability) XXX_Size() int {
	return m.Size()
}
func (m *Capability) XXX_DiscardUnknown() {
	xxx_messageInfo_Capability.DiscardUnknown(m)
}

var xxx_messageInfo_Capability proto.InternalMessageInfo

// Invocation represents a single invocation of a capability.
type Invocation struct {
	// id is the unique identifier of the invocation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// capability_id is the ID of the invoked capability.
	CapabilityId string `protobuf:"bytes,2,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	// consumer is the address of the invoker.
	Consumer string `protobuf:"bytes,3,opt,name=consumer,proto3" json:"consumer,omitempty"`
	// provider is the address of the capability provider.
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// input_hash is the hash of the invocation input.
	InputHash string `protobuf:"bytes,5,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	// output_hash is the hash of the invocation output.
	OutputHash string `protobuf:"bytes,6,opt,name=output_hash,json=outputHash,proto3" json:"output_hash,omitempty"`
	// status is the current status of the invocation.
	Status InvocationStatus `protobuf:"varint,7,opt,name=status,proto3,enum=oasyce.capability.v1.InvocationStatus" json:"status,omitempty"`
	// amount is the cost of the invocation.
	Amount types.Coin `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount"`
	// timestamp is the time the invocation was created.
	Timestamp time.Time `protobuf:"bytes,9,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	// escrow_id is the ID of the escrow backing this invocation.
	EscrowId string `protobuf:"bytes,10,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
}

func (m *Invocation) Reset()         { *m = Invocation{} }
func (m *Invocation) String() string { return proto.CompactTextString(m) }
func (*Invocation) ProtoMessage()    {}
func (*Invocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_81373fc0ccc58e21, []int{1}
}
func (m *Invocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Invocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Invocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Invocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invocation.Merge(m, src)
}
func (m *Invocation) XXX_Size() int {
	return m.Size()
}
func (m *Invocation) XXX_DiscardUnknown() {
	xxx_messageInfo_Invocation.DiscardUnknown(m)
}

var xxx_messageInfo_Invocation proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("oasyce.capability.v1.InvocationStatus", InvocationStatus_name, InvocationStatus_value)
	proto.RegisterType((*Capability)(nil), "oasyce.capability.v1.Capability")
	proto.RegisterType((*Invocation)(nil), "oasyce.capability.v1.Invocation")
}

func init() { proto.RegisterFile("oasyce/capability/v1/types.proto", fileDescriptor_81373fc0ccc58e21) }

var fileDescriptor_81373fc0ccc58e21 = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x8f, 0xdb, 0x44,
	0x14, 0xc7, 0xe3, 0xdd, 0x10, 0x92, 0x97, 0x6c, 0x14, 0x8d, 0x16, 0xc9, 0xbb, 0xb0, 0x49, 0x5a,
	0x10, 0x8a, 0x8a, 0x6a, 0x6b, 0x0b, 0x12, 0x12, 0x07, 0xa4, 0x24, 0x9b, 0x82, 0xa5, 0x25, 0x5d,
	0x39, 0xbb, 0x1c, 0xb8, 0x58, 0x13, 0x7b, 0x70, 0x46, 0xd8, 0x33, 0x96, 0x67, 0x6c, 0xd8, 0x6f,
	0xd0, 0x63, 0x6f, 0x5c, 0x2b, 0xf1, 0x15, 0xfa, 0x21, 0x2a, 0x71, 0x29, 0x3d, 0x21, 0x0e, 0x05,
	0xed, 0x5e, 0xf8, 0x18, 0x68, 0x66, 0x9c, 0xa4, 0xb4, 0xab, 0x6a, 0x6f, 0x33, 0xff, 0xf7, 0x7f,
	0x9e, 0xe7, 0xf7, 0x7e, 0x33, 0x30, 0xe4, 0x58, 0x5c, 0x86, 0xc4, 0x0d, 0x71, 0x86, 0x97, 0x34,
	0xa1, 0xf2, 0xd2, 0x2d, 0x8f, 0x5d, 0x79, 0x99, 0x11, 0xe1, 0x64, 0x39, 0x97, 0x1c, 0xed, 0x1b,
	0x87, 0xb3, 0x75, 0x38, 0xe5, 0xf1, 0x61, 0x3f, 0xe4, 0x22, 0xe5, 0xc2, 0x5d, 0x62, 0x41, 0xdc,
	0xf2, 0x78, 0x49, 0x24, 0x3e, 0x76, 0x43, 0x4e, 0x99, 0xc9, 0x3a, 0x3c, 0x30, 0xf1, 0x40, 0xef,
	0x5c, 0xb3, 0xa9, 0x42, 0xfb, 0x31, 0x8f, 0xb9, 0xd1, 0xd5, 0xaa, 0x52, 0x07, 0x31, 0xe7, 0x71,
	0x42, 0x5c, 0xbd, 0x5b, 0x16, 0x3f, 0xba, 0x92, 0xa6, 0x44, 0x48, 0x9c, 0x66, 0xc6, 0x70, 0xf7,
	0xf7, 0x3a, 0xc0, 0x74, 0x53, 0x03, 0xea, 0xc2, 0x0e, 0x8d, 0x6c, 0x6b, 0x68, 0x8d, 0x5a, 0xfe,
	0x0e, 0x8d, 0xd0, 0x17, 0xd0, 0xcc, 0x72, 0x5e, 0xd2, 0x88, 0xe4, 0xf6, 0x8e, 0x52, 0x27, 0xf6,
	0xcb, 0x67, 0xf7, 0xf7, 0xab, 0x93, 0xc7, 0x51, 0x94, 0x13, 0x21, 0x16, 0x32, 0xa7, 0x2c, 0xf6,
	0x37, 0x4e, 0x84, 0xa0, 0xce, 0x70, 0x4a, 0xec, 0x5d, 0xfd, 0x1d, 0xbd, 0x46, 0x43, 0x68, 0x47,
	0x44, 0x84, 0x39, 0xcd, 0x24, 0xe5, 0xcc, 0xae, 0xeb, 0xd0, 0xeb, 0x12, 0xba, 0x03, 0x1d, 0xc2,
	0xa2, 0x8c, 0x53, 0x26, 0x83, 0x22, 0x4f, 0xec, 0xf7, 0x8c, 0x65, 0xad, 0x5d, 0xe4, 0x09, 0x9a,
	0x41, 0x37, 0xcb, 0x69, 0x48, 0x82, 0x8c, 0xe4, 0x41, 0x88, 0x93, 0xc4, 0x6e, 0x0c, 0xad, 0x51,
	0xfb, 0xc1, 0x81, 0x53, 0x55, 0xa4, 0x1a, 0xe7, 0x54, 0x8d, 0x73, 0xa6, 0x9c, 0xb2, 0x49, 0xfd,
	0xf9, 0xab, 0x41, 0xcd, 0xef, 0xe8, 0xb4, 0x33, 0x92, 0x4f, 0x71, 0x92, 0xa8, 0xfa, 0x24, 0x8e,
	0x85, 0xfd, 0xfe, 0x70, 0x57, 0xd5, 0xa7, 0xd6, 0xe8, 0x08, 0x20, 0xc7, 0x92, 0x04, 0x09, 0x4d,
	0xa9, 0xb4, 0x9b, 0x43, 0x6b, 0x54, 0xf7, 0x5b, 0x4a, 0x39, 0x55, 0x02, 0x1a, 0x40, 0x5b, 0x72,
	0x89, 0x13, 0x7d, 0xaa, 0xb0, 0x5b, 0x3a, 0x0e, 0x5a, 0x52, 0x9f, 0x14, 0x68, 0x0e, 0x1d, 0x63,
	0x20, 0x38, 0x67, 0x24, 0xb2, 0x41, 0x77, 0xeb, 0x33, 0x75, 0xfa, 0x5f, 0xaf, 0x06, 0x1f, 0x98,
	0xfa, 0x44, 0xf4, 0x93, 0x43, 0xb9, 0x9b, 0x62, 0xb9, 0x72, 0x3c, 0x26, 0x5f, 0x3e, 0xbb, 0x0f,
	0x55, 0xe1, 0x1e, 0x93, 0xbe, 0x39, 0x61, 0xa6, 0xf3, 0xd1, 0x27, 0xd0, 0xc5, 0x65, 0x1c, 0x24,
	0x58, 0x12, 0x16, 0x5e, 0x06, 0xa9, 0xb0, 0xdb, 0xfa, 0xcc, 0x0e, 0x2e, 0xe3, 0x53, 0x23, 0x7e,
	0x27, 0x54, 0xcf, 0x44, 0x11, 0x86, 0x44, 0x88, 0x40, 0xd5, 0x6a, 0x77, 0x86, 0xd6, 0x68, 0xcf,
	0x6f, 0x57, 0x9a, 0x8f, 0x25, 0x41, 0x1f, 0x42, 0x8b, 0x8a, 0x00, 0x87, 0x92, 0x96, 0xc4, 0xde,
	0x1b, 0x5a, 0xa3, 0xa6, 0xdf, 0xa4, 0x62, 0xac, 0xf7, 0x68, 0x0a, 0x10, 0xe6, 0x04, 0x4b, 0x12,
	0x05, 0x58, 0xda, 0x5d, 0xdd, 0xcc, 0x43, 0xc7, 0x40, 0xe3, 0xac, 0xa1, 0x71, 0xce, 0xd7, 0xd0,
	0x4c, 0x9a, 0xea, 0x7f, 0x9e, 0xfc, 0x3d, 0xb0, 0xfc, 0x56, 0x95, 0x37, 0x96, 0x5f, 0x35, 0x1f,
	0x3f, 0x1d, 0xd4, 0xfe, 0x7d, 0x3a, 0xa8, 0xdd, 0xfd, 0x63, 0x17, 0xc0, 0x63, 0x25, 0x0f, 0xb1,
	0x9e, 0xe8, 0x9b, 0x34, 0x7d, 0x0c, 0x7b, 0x5b, 0xde, 0x03, 0x1a, 0x19, 0xa4, 0xfc, 0xce, 0x56,
	0xf4, 0x34, 0x72, 0x21, 0x67, 0xa2, 0x48, 0x49, 0x6e, 0x00, 0x7a, 0x17, 0x72, 0x6b, 0xe7, 0xff,
	0x40, 0xad, 0xdf, 0x1a, 0xd4, 0x23, 0x00, 0xca, 0xb2, 0x42, 0x06, 0x2b, 0x2c, 0x56, 0x15, 0x70,
	0x2d, 0xad, 0x7c, 0x8b, 0xc5, 0x4a, 0x0d, 0x9d, 0x17, 0x72, 0x13, 0x6f, 0xe8, 0x38, 0x18, 0x49,
	0x1b, 0xbe, 0x86, 0x86, 0x90, 0x58, 0x16, 0x0a, 0x25, 0x6b, 0xd4, 0x7d, 0xf0, 0xa9, 0x73, 0xd3,
	0xb5, 0x76, 0xb6, 0x2d, 0x59, 0x68, 0xb7, 0x5f, 0x65, 0xa1, 0x2f, 0xa1, 0x81, 0x53, 0x5e, 0x30,
	0x03, 0xdc, 0x2d, 0x38, 0xae, 0xec, 0x68, 0x02, 0xad, 0xcd, 0x4d, 0xd6, 0x30, 0xde, 0x7a, 0x6c,
	0x9b, 0x34, 0x05, 0x86, 0xba, 0x7d, 0xfc, 0x67, 0x35, 0x09, 0x8d, 0xab, 0xdf, 0x34, 0x82, 0x17,
	0x6d, 0x67, 0x7a, 0xef, 0x57, 0x0b, 0x7a, 0x6f, 0xfe, 0x00, 0xba, 0x03, 0x47, 0xde, 0xfc, 0xfb,
	0x47, 0xd3, 0xf1, 0xb9, 0xf7, 0x68, 0x1e, 0x2c, 0xce, 0xc7, 0xe7, 0x17, 0x8b, 0xe0, 0x62, 0xbe,
	0x38, 0x9b, 0x4d, 0xbd, 0x87, 0xde, 0xec, 0xa4, 0x57, 0x43, 0x47, 0x70, 0xf0, 0xb6, 0xe5, 0x6c,
	0x36, 0x3f, 0xf1, 0xe6, 0xdf, 0xf4, 0xac, 0x9b, 0xc3, 0x8b, 0x8b, 0xe9, 0x74, 0xb6, 0x58, 0xf4,
	0x76, 0xd0, 0x47, 0x60, 0xbf, 0x1d, 0x7e, 0x38, 0xf6, 0x4e, 0x67, 0x27, 0xbd, 0xdd, 0xc3, 0xfa,
	0xe3, 0xdf, 0xfa, 0xb5, 0xc9, 0xc9, 0xf3, 0xab, 0xbe, 0xf5, 0xe2, 0xaa, 0x6f, 0xfd, 0x73, 0xd5,
	0xb7, 0x9e, 0x5c, 0xf7, 0x6b, 0x2f, 0xae, 0xfb, 0xb5, 0x3f, 0xaf, 0xfb, 0xb5, 0x1f, 0xee, 0xc5,
	0x54, 0xae, 0x8a, 0xa5, 0x13, 0xf2, 0xd4, 0x5d, 0x3f, 0xc5, 0x2b, 0x4c, 0x99, 0xfb, 0xcb, 0xeb,
	0x4f, 0xb2, 0x7e, 0x8f, 0x97, 0x0d, 0xdd, 0xaf, 0xcf, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x25,
	0x49, 0x74, 0xee, 0xb4, 0x05, 0x00, 0x00,
}

func (m *Capability) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Capability) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Capability) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTypes(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x72
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.SuccessRate != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SuccessRate))
		i--
		dAtA[i] = 0x60
	}
	if m.AvgLatencyMs != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AvgLatencyMs))
		i--
		dAtA[i] = 0x58
	}
	{
		size := m.TotalEarned.Size()
		i -= size
		if _, err := m.TotalEarned.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.TotalCalls != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TotalCalls))
		i--
		dAtA[i] = 0x48
	}
	if m.RateLimit != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RateLimit))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Tags) > 0 {
		for iNdEx := len(m.Tags) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Tags[iNdEx])
			copy(dAtA[i:], m.Tags[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Tags[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	{
		size, err := m.PricePerCall.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.EndpointUrl) > 0 {
		i -= len(m.EndpointUrl)
		copy(dAtA[i:], m.EndpointUrl)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.EndpointUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Invocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Invocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Invocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EscrowId) > 0 {
		i -= len(m.EscrowId)
		copy(dAtA[i:], m.EscrowId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.EscrowId)))
		i--
		dAtA[i] = 0x52
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintTypes(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x4a
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if len(m.OutputHash) > 0 {
		i -= len(m.OutputHash)
		copy(dAtA[i:], m.OutputHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OutputHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.InputHash) > 0 {
		i -= len(m.InputHash)
		copy(dAtA[i:], m.InputHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.InputHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Consumer) > 0 {
		i -= len(m.Consumer)
		copy(dAtA[i:], m.Consumer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Consumer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CapabilityId) > 0 {
		i -= len(m.CapabilityId)
		copy(dAtA[i:], m.CapabilityId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CapabilityId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Capability) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.EndpointUrl)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.PricePerCall.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Tags) > 0 {
		for _, s := range m.Tags {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.RateLimit != 0 {
		n += 1 + sovTypes(uint64(m.RateLimit))
	}
	if m.TotalCalls != 0 {
		n += 1 + sovTypes(uint64(m.TotalCalls))
	}
	l = m.TotalEarned.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.AvgLatencyMs != 0 {
		n += 1 + sovTypes(uint64(m.AvgLatencyMs))
	}
	if m.SuccessRate != 0 {
		n += 1 + sovTypes(uint64(m.SuccessRate))
	}
	if m.IsActive {
		n += 2
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *Invocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CapabilityId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Consumer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.InputHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OutputHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovTypes(uint64(l))
	l = len(m.EscrowId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Capability) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Capability: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Capability: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndpointUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndpointUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePerCall", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PricePerCall.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimit", wireType)
			}
			m.RateLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RateLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCalls", wireType)
			}
			m.TotalCalls = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCalls |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalEarned", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalEarned.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvgLatencyMs", wireType)
			}
			m.AvgLatencyMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvgLatencyMs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SuccessRate", wireType)
			}
			m.SuccessRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SuccessRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Invocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Invocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Invocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CapabilityId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CapabilityId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Consumer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Consumer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InputHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InputHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutputHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutputHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= InvocationStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EscrowId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EscrowId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
