// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/delegate/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EnrollmentMode defines how delegates can join a policy.
type EnrollmentMode int32

const (
	// ENROLLMENT_MODE_UNSPECIFIED is invalid.
	ENROLLMENT_MODE_UNSPECIFIED EnrollmentMode = 0
	// ENROLLMENT_MODE_TOKEN requires a shared token to enroll.
	ENROLLMENT_MODE_TOKEN EnrollmentMode = 1
	// ENROLLMENT_MODE_OPEN allows anyone to enroll (risk bounded by spend cap).
	ENROLLMENT_MODE_OPEN EnrollmentMode = 2
)

var EnrollmentMode_name = map[int32]string{
	0: "ENROLLMENT_MODE_UNSPECIFIED",
	1: "ENROLLMENT_MODE_TOKEN",
	2: "ENROLLMENT_MODE_OPEN",
}

var EnrollmentMode_value = map[string]int32{
	"ENROLLMENT_MODE_UNSPECIFIED": 0,
	"ENROLLMENT_MODE_TOKEN":       1,
	"ENROLLMENT_MODE_OPEN":        2,
}

func (x EnrollmentMode) String() string {
	return proto.EnumName(EnrollmentMode_name, int32(x))
}

func (EnrollmentMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_720a483a63be4831, []int{0}
}

// DelegatePolicy defines spending rules set by a principal for all delegates.
// One principal, one policy. All delegates share the same budget.
type DelegatePolicy struct {
	// principal is the account that owns the assets.
	Principal string `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	// per_tx_limit is the maximum spend per single MsgExec.
	PerTxLimit types.Coin `protobuf:"bytes,2,opt,name=per_tx_limit,json=perTxLimit,proto3" json:"per_tx_limit"`
	// window_limit is the total spend cap within one window period.
	WindowLimit types.Coin `protobuf:"bytes,3,opt,name=window_limit,json=windowLimit,proto3" json:"window_limit"`
	// window_seconds is the budget reset interval (default 86400 = 1 day).
	WindowSeconds uint64 `protobuf:"varint,4,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	// allowed_msgs is the list of message type URLs delegates can execute.
	AllowedMsgs []string `protobuf:"bytes,5,rep,name=allowed_msgs,json=allowedMsgs,proto3" json:"allowed_msgs,omitempty"`
	// enrollment_mode controls how new delegates join.
	EnrollmentMode EnrollmentMode `protobuf:"varint,6,opt,name=enrollment_mode,json=enrollmentMode,proto3,enum=oasyce.delegate.v1.EnrollmentMode" json:"enrollment_mode,omitempty"`
	// enrollment_token_hash is sha256(token) for TOKEN mode enrollment.
	EnrollmentTokenHash []byte `protobuf:"bytes,7,opt,name=enrollment_token_hash,json=enrollmentTokenHash,proto3" json:"enrollment_token_hash,omitempty"`
	// expiration_seconds is seconds from creation until policy expires (0 = no expiry).
	ExpirationSeconds uint64 `protobuf:"varint,8,opt,name=expiration_seconds,json=expirationSeconds,proto3" json:"expiration_seconds,omitempty"`
	// created_at_seconds is the block time when policy was created (unix).
	CreatedAtSeconds int64 `protobuf:"varint,9,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
}

func (m *DelegatePolicy) Reset()         { *m = DelegatePolicy{} }
func (m *DelegatePolicy) String() string { return proto.CompactTextString(m) }
func (*DelegatePolicy) ProtoMessage()    {}
func (*DelegatePolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_720a483a63be4831, []int{0}
}
func (m *DelegatePolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegatePolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegatePolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegatePolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegatePolicy.Merge(m, src)
}
func (m *DelegatePolicy) XXX_Size() int {
	return m.Size()
}
func (m *DelegatePolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegatePolicy.DiscardUnknown(m)
}

var xxx_messageInfo_DelegatePolicy proto.InternalMessageInfo

// DelegateRecord is a single enrolled delegate.
type DelegateRecord struct {
	// delegate is the agent's address.
	Delegate string `protobuf:"bytes,1,opt,name=delegate,proto3" json:"delegate,omitempty"`
	// principal is the owning account.
	Principal string `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	// label is an optional human-readable tag (e.g. "macbook-agent-1").
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// enrolled_at_seconds is the enrollment time (unix).
	EnrolledAtSeconds int64 `protobuf:"varint,4,opt,name=enrolled_at_seconds,json=enrolledAtSeconds,proto3" json:"enrolled_at_seconds,omitempty"`
}

func (m *DelegateRecord) Reset()         { *m = DelegateRecord{} }
func (m *DelegateRecord) String() string { return proto.CompactTextString(m) }
func (*DelegateRecord) ProtoMessage()    {}
func (*DelegateRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_720a483a63be4831, []int{1}
}
func (m *DelegateRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegateRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegateRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegateRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegateRecord.Merge(m, src)
}
func (m *DelegateRecord) XXX_Size() int {
	return m.Size()
}
func (m *DelegateRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegateRecord.DiscardUnknown(m)
}

var xxx_messageInfo_DelegateRecord proto.InternalMessageInfo

// SpendWindow tracks cumulative spending within a time window.
type SpendWindow struct {
	// principal whose budget this tracks.
	Principal string `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	// window_start is the start of the current window (unix seconds).
	WindowStart int64 `protobuf:"varint,2,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	// spent is the cumulative amount spent in this window.
	Spent types.Coin `protobuf:"bytes,3,opt,name=spent,proto3" json:"spent"`
}

func (m *SpendWindow) Reset()         { *m = SpendWindow{} }
func (m *SpendWindow) String() string { return proto.CompactTextString(m) }
func (*SpendWindow) ProtoMessage()    {}
func (*SpendWindow) Descriptor() ([]byte, []int) {
	return fileDescriptor_720a483a63be4831, []int{2}
}
func (m *SpendWindow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpendWindow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpendWindow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpendWindow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpendWindow.Merge(m, src)
}
func (m *SpendWindow) XXX_Size() int {
	return m.Size()
}
func (m *SpendWindow) XXX_DiscardUnknown() {
	xxx_messageInfo_SpendWindow.DiscardUnknown(m)
}

var xxx_messageInfo_SpendWindow proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("oasyce.delegate.v1.EnrollmentMode", EnrollmentMode_name, EnrollmentMode_value)
	proto.RegisterType((*DelegatePolicy)(nil), "oasyce.delegate.v1.DelegatePolicy")
	proto.RegisterType((*DelegateRecord)(nil), "oasyce.delegate.v1.DelegateRecord")
	proto.RegisterType((*SpendWindow)(nil), "oasyce.delegate.v1.SpendWindow")
}

func init() { proto.RegisterFile("oasyce/delegate/v1/types.proto", fileDescriptor_720a483a63be4831) }

var fileDescriptor_720a483a63be4831 = []byte{
	// 642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6b, 0xdb, 0x4a,
	0x14, 0xd5, 0xc4, 0x4e, 0x5e, 0x3c, 0xf6, 0xf3, 0x73, 0xe6, 0x39, 0xa0, 0xe4, 0x81, 0xac, 0x04,
	0x1e, 0x88, 0xd2, 0x48, 0x24, 0xfd, 0x58, 0x74, 0x17, 0x27, 0x2a, 0x0d, 0x89, 0xed, 0x20, 0xbb,
	0x14, 0xba, 0x11, 0x63, 0x69, 0x90, 0x87, 0xca, 0x33, 0x42, 0x33, 0x4d, 0x9c, 0x65, 0x77, 0x59,
	0xf6, 0x27, 0x04, 0xba, 0xea, 0xbe, 0x3f, 0x22, 0xab, 0x12, 0xba, 0xea, 0xaa, 0x94, 0x64, 0xd3,
	0x9f, 0x51, 0xac, 0x91, 0xed, 0x3a, 0x2d, 0x34, 0x74, 0xa7, 0x7b, 0xcf, 0xb9, 0x67, 0xe6, 0x68,
	0x0e, 0x17, 0x1a, 0x1c, 0x8b, 0xb3, 0x80, 0x38, 0x21, 0x89, 0x49, 0x84, 0x25, 0x71, 0x4e, 0xb6,
	0x1d, 0x79, 0x96, 0x10, 0x61, 0x27, 0x29, 0x97, 0x1c, 0x21, 0x85, 0xdb, 0x13, 0xdc, 0x3e, 0xd9,
	0x5e, 0x5f, 0x0b, 0xb8, 0x18, 0x72, 0xe1, 0x67, 0x0c, 0x47, 0x15, 0x8a, 0xbe, 0x6e, 0xa8, 0xca,
	0xe9, 0x63, 0x31, 0x96, 0xea, 0x13, 0x89, 0xb7, 0x9d, 0x80, 0x53, 0x96, 0xe3, 0xf5, 0x88, 0x47,
	0x5c, 0xcd, 0x8d, 0xbf, 0x54, 0x77, 0xf3, 0x4d, 0x11, 0x56, 0xf7, 0xf3, 0x03, 0x8e, 0x79, 0x4c,
	0x83, 0x33, 0xf4, 0x18, 0x96, 0x92, 0x94, 0xb2, 0x80, 0x26, 0x38, 0xd6, 0x81, 0x09, 0xac, 0x52,
	0x53, 0xff, 0xf4, 0x61, 0xab, 0x9e, 0x9f, 0xb6, 0x1b, 0x86, 0x29, 0x11, 0xa2, 0x2b, 0x53, 0xca,
	0x22, 0x6f, 0x46, 0x45, 0xbb, 0xb0, 0x92, 0x90, 0xd4, 0x97, 0x23, 0x3f, 0xa6, 0x43, 0x2a, 0xf5,
	0x05, 0x13, 0x58, 0xe5, 0x9d, 0x35, 0x3b, 0x9f, 0x1b, 0xdf, 0xcb, 0xce, 0xef, 0x65, 0xef, 0x71,
	0xca, 0x9a, 0xc5, 0xcb, 0x2f, 0x0d, 0xcd, 0x83, 0x09, 0x49, 0x7b, 0xa3, 0xa3, 0xf1, 0x08, 0x6a,
	0xc2, 0xca, 0x29, 0x65, 0x21, 0x3f, 0xcd, 0x25, 0x0a, 0x77, 0x93, 0x28, 0xab, 0x21, 0xa5, 0xf1,
	0x3f, 0xac, 0xe6, 0x1a, 0x82, 0x04, 0x9c, 0x85, 0x42, 0x2f, 0x9a, 0xc0, 0x2a, 0x7a, 0x7f, 0xab,
	0x6e, 0x57, 0x35, 0xd1, 0x06, 0xac, 0xe0, 0x38, 0xe6, 0xa7, 0x24, 0xf4, 0x87, 0x22, 0x12, 0xfa,
	0xa2, 0x59, 0xb0, 0x4a, 0x5e, 0x39, 0xef, 0xb5, 0x44, 0x24, 0xd0, 0x21, 0xfc, 0x87, 0xb0, 0x94,
	0xc7, 0xf1, 0x90, 0x30, 0xe9, 0x0f, 0x79, 0x48, 0xf4, 0x25, 0x13, 0x58, 0xd5, 0x9d, 0x4d, 0xfb,
	0xe7, 0xa7, 0xb1, 0xdd, 0x29, 0xb5, 0xc5, 0x43, 0xe2, 0x55, 0xc9, 0x5c, 0x8d, 0x76, 0xe0, 0xea,
	0x0f, 0x62, 0x92, 0xbf, 0x22, 0xcc, 0x1f, 0x60, 0x31, 0xd0, 0xff, 0x32, 0x81, 0x55, 0xf1, 0xfe,
	0x9d, 0x81, 0xbd, 0x31, 0xf6, 0x0c, 0x8b, 0x01, 0xda, 0x82, 0x88, 0x8c, 0x12, 0x9a, 0x62, 0x49,
	0x39, 0x9b, 0xda, 0x59, 0xce, 0xec, 0xac, 0xcc, 0x90, 0x89, 0xa5, 0xfb, 0x10, 0x05, 0x29, 0xc1,
	0x92, 0x84, 0x3e, 0x96, 0x53, 0x7a, 0xc9, 0x04, 0x56, 0xc1, 0xab, 0xe5, 0xc8, 0xae, 0xcc, 0xd9,
	0x4f, 0x96, 0xcf, 0x2f, 0x1a, 0xda, 0xb7, 0x8b, 0x86, 0xb6, 0xf9, 0x11, 0xcc, 0x32, 0xe0, 0x91,
	0x80, 0xa7, 0x21, 0x7a, 0x08, 0x97, 0x27, 0xde, 0x7e, 0x1b, 0x81, 0x29, 0x73, 0x3e, 0x39, 0x0b,
	0x77, 0x4f, 0x4e, 0x1d, 0x2e, 0xc6, 0xb8, 0x4f, 0xe2, 0xec, 0xbd, 0x4b, 0x9e, 0x2a, 0x90, 0x0d,
	0xf3, 0x9f, 0x32, 0xef, 0xa7, 0x98, 0xf9, 0x59, 0x99, 0x40, 0xbf, 0x32, 0xf4, 0x1e, 0xc0, 0x72,
	0x37, 0x21, 0x2c, 0x7c, 0x91, 0x3d, 0xf9, 0x1f, 0x27, 0x7a, 0x63, 0x1a, 0x47, 0x21, 0x71, 0xaa,
	0x12, 0x5d, 0x98, 0xa4, 0xad, 0x3b, 0x6e, 0xa1, 0x47, 0x70, 0x51, 0x24, 0x84, 0xdd, 0x39, 0xaa,
	0x8a, 0x3d, 0xbb, 0xeb, 0xbd, 0x18, 0x56, 0xe7, 0x93, 0x83, 0x1a, 0xf0, 0x3f, 0xb7, 0xed, 0x75,
	0x8e, 0x8e, 0x5a, 0x6e, 0xbb, 0xe7, 0xb7, 0x3a, 0xfb, 0xae, 0xff, 0xbc, 0xdd, 0x3d, 0x76, 0xf7,
	0x0e, 0x9e, 0x1e, 0xb8, 0xfb, 0x35, 0x0d, 0xad, 0xc1, 0xd5, 0xdb, 0x84, 0x5e, 0xe7, 0xd0, 0x6d,
	0xd7, 0x00, 0xd2, 0x61, 0xfd, 0x36, 0xd4, 0x39, 0x76, 0xdb, 0xb5, 0x85, 0xf5, 0xe2, 0xf9, 0x3b,
	0x43, 0x6b, 0x36, 0x2f, 0xaf, 0x0d, 0x70, 0x75, 0x6d, 0x80, 0xaf, 0xd7, 0x06, 0x78, 0x7b, 0x63,
	0x68, 0x57, 0x37, 0x86, 0xf6, 0xf9, 0xc6, 0xd0, 0x5e, 0x5a, 0x11, 0x95, 0x83, 0xd7, 0x7d, 0x3b,
	0xe0, 0x43, 0x27, 0x5f, 0x4c, 0xc1, 0x00, 0x53, 0xe6, 0x8c, 0x66, 0x0b, 0x2a, 0xdb, 0x4e, 0xfd,
	0xa5, 0x6c, 0x73, 0x3c, 0xf8, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x6d, 0xbc, 0x57, 0xc0, 0x04,
	0x00, 0x00,
}

func (m *DelegatePolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegatePolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegatePolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAtSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CreatedAtSeconds))
		i--
		dAtA[i] = 0x48
	}
	if m.ExpirationSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpirationSeconds))
		i--
		dAtA[i] = 0x40
	}
	if len(m.EnrollmentTokenHash) > 0 {
		i -= len(m.EnrollmentTokenHash)
		copy(dAtA[i:], m.EnrollmentTokenHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.EnrollmentTokenHash)))
		i--
		dAtA[i] = 0x3a
	}
	if m.EnrollmentMode != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EnrollmentMode))
		i--
		dAtA[i] = 0x30
	}
	if len(m.AllowedMsgs) > 0 {
		for iNdEx := len(m.AllowedMsgs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AllowedMsgs[iNdEx])
			copy(dAtA[i:], m.AllowedMsgs[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.AllowedMsgs[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.WindowSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.WindowSeconds))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.WindowLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.PerTxLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Principal) > 0 {
		i -= len(m.Principal)
		copy(dAtA[i:], m.Principal)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Principal)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DelegateRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegateRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegateRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EnrolledAtSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EnrolledAtSeconds))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Principal) > 0 {
		i -= len(m.Principal)
		copy(dAtA[i:], m.Principal)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Principal)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Delegate) > 0 {
		i -= len(m.Delegate)
		copy(dAtA[i:], m.Delegate)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Delegate)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SpendWindow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpendWindow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpendWindow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Spent.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.WindowStart != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.WindowStart))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Principal) > 0 {
		i -= len(m.Principal)
		copy(dAtA[i:], m.Principal)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Principal)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegatePolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Principal)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.PerTxLimit.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.WindowLimit.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.WindowSeconds != 0 {
		n += 1 + sovTypes(uint64(m.WindowSeconds))
	}
	if len(m.AllowedMsgs) > 0 {
		for _, s := range m.AllowedMsgs {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.EnrollmentMode != 0 {
		n += 1 + sovTypes(uint64(m.EnrollmentMode))
	}
	l = len(m.EnrollmentTokenHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ExpirationSeconds != 0 {
		n += 1 + sovTypes(uint64(m.ExpirationSeconds))
	}
	if m.CreatedAtSeconds != 0 {
		n += 1 + sovTypes(uint64(m.CreatedAtSeconds))
	}
	return n
}

func (m *DelegateRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegate)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Principal)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.EnrolledAtSeconds != 0 {
		n += 1 + sovTypes(uint64(m.EnrolledAtSeconds))
	}
	return n
}

func (m *SpendWindow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Principal)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.WindowStart != 0 {
		n += 1 + sovTypes(uint64(m.WindowStart))
	}
	l = m.Spent.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegatePolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegatePolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegatePolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Principal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerTxLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PerTxLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WindowLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WindowLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WindowSeconds", wireType)
			}
			m.WindowSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WindowSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowedMsgs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllowedMsgs = append(m.AllowedMsgs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnrollmentMode", wireType)
			}
			m.EnrollmentMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnrollmentMode |= EnrollmentMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnrollmentTokenHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EnrollmentTokenHash = append(m.EnrollmentTokenHash[:0], dAtA[iNdEx:postIndex]...)
			if m.EnrollmentTokenHash == nil {
				m.EnrollmentTokenHash = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpirationSeconds", wireType)
			}
			m.ExpirationSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpirationSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtSeconds", wireType)
			}
			m.CreatedAtSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegateRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegateRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegateRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Principal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnrolledAtSeconds", wireType)
			}
			m.EnrolledAtSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnrolledAtSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SpendWindow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpendWindow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpendWindow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Principal = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WindowStart", wireType)
			}
			m.WindowStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WindowStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
