package types

import "cosmossdk.io/errors"

var (
	ErrAssetNotFound     = errors.Register(ModuleName, 2, "data asset not found")
	ErrDisputeNotFound   = errors.Register(ModuleName, 3, "dispute not found")
	ErrNotArbitrator     = errors.Register(ModuleName, 4, "caller is not the arbitrator")
	ErrAssetDelisted     = errors.Register(ModuleName, 5, "data asset is delisted")
	ErrInvalidCoCreators = errors.Register(ModuleName, 6, "invalid co-creators")
	ErrInvalidAddress    = errors.Register(ModuleName, 7, "invalid address")
	ErrInsufficientFunds = errors.Register(ModuleName, 8, "insufficient funds")
	ErrInvalidParams     = errors.Register(ModuleName, 9, "invalid params")
	ErrUnauthorized      = errors.Register(ModuleName, 10, "unauthorized")
	ErrInvalidRightsType = errors.Register(ModuleName, 11, "invalid rights type")
	ErrDisputeNotOpen    = errors.Register(ModuleName, 12, "dispute is not open")
	ErrDuplicateAsset        = errors.Register(ModuleName, 13, "duplicate content hash")
	ErrContentHashMismatch   = errors.Register(ModuleName, 14, "content hash mismatch")
	ErrSlippageExceeded      = errors.Register(ModuleName, 15, "slippage tolerance exceeded")
	ErrAssetShuttingDown     = errors.Register(ModuleName, 16, "asset is shutting down")
	ErrAssetSettled          = errors.Register(ModuleName, 17, "asset is already settled")
	ErrCooldownNotElapsed    = errors.Register(ModuleName, 18, "shutdown cooldown has not elapsed")
	ErrNoSharesHeld          = errors.Register(ModuleName, 19, "caller holds no shares of this asset")
	ErrAssetNotShuttingDown  = errors.Register(ModuleName, 20, "asset is not in shutting down state")
	ErrMigrationNotFound     = errors.Register(ModuleName, 21, "migration path not found")
	ErrMigrationDisabled     = errors.Register(ModuleName, 22, "migration path is disabled")
	ErrMigrationCapExceeded  = errors.Register(ModuleName, 23, "migration cap exceeded")
	ErrInvalidVersion        = errors.Register(ModuleName, 24, "invalid asset version")
	ErrMigrationExists       = errors.Register(ModuleName, 25, "migration path already exists")
)
