// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/datarights/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterDataAsset registers a new data asset on-chain.
type MsgRegisterDataAsset struct {
	// creator is the address of the data asset owner.
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// name is the human-readable name of the data asset.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// description is a detailed description of the data asset.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// content_hash is the hash of the data asset content.
	ContentHash string `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// rights_type is the rights classification.
	RightsType RightsType `protobuf:"varint,5,opt,name=rights_type,json=rightsType,proto3,enum=oasyce.datarights.v1.RightsType" json:"rights_type,omitempty"`
	// tags are searchable labels for the data asset.
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// co_creators is the list of co-creators and their share allocations.
	CoCreators []CoCreator `protobuf:"bytes,7,rep,name=co_creators,json=coCreators,proto3" json:"co_creators"`
}

func (m *MsgRegisterDataAsset) Reset()         { *m = MsgRegisterDataAsset{} }
func (m *MsgRegisterDataAsset) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDataAsset) ProtoMessage()    {}
func (*MsgRegisterDataAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4554f457b53c7be, []int{0}
}
func (m *MsgRegisterDataAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDataAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDataAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDataAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDataAsset.Merge(m, src)
}
func (m *MsgRegisterDataAsset) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDataAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDataAsset.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDataAsset proto.InternalMessageInfo

func (m *MsgRegisterDataAsset) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterDataAsset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgRegisterDataAsset) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgRegisterDataAsset) GetContentHash() string {
	if m != nil {
		return m.ContentHash
	}
	return ""
}

func (m *MsgRegisterDataAsset) GetRightsType() RightsType {
	if m != nil {
		return m.RightsType
	}
	return RIGHTS_TYPE_UNSPECIFIED
}

func (m *MsgRegisterDataAsset) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MsgRegisterDataAsset) GetCoCreators() []CoCreator {
	if m != nil {
		return m.CoCreators
	}
	return nil
}

// MsgRegisterDataAssetResponse is the response for MsgRegisterDataAsset.
type MsgRegisterDataAssetResponse struct {
	// asset_id is the unique identifier of the registered data asset.
	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
}

func (m *MsgRegisterDataAssetResponse) Reset()         { *m = MsgRegisterDataAssetResponse{} }
func (m *MsgRegisterDataAssetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDataAssetResponse) ProtoMessage()    {}
func (*MsgRegisterDataAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4554f457b53c7be, []int{1}
}
func (m *MsgRegisterDataAssetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDataAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDataAssetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDataAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDataAssetResponse.Merge(m, src)
}
func (m *MsgRegisterDataAssetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDataAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDataAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDataAssetResponse proto.InternalMessageInfo

func (m *MsgRegisterDataAssetResponse) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

// MsgBuyShares purchases shares of a data asset via bonding curve.
type MsgBuyShares struct {
	// creator is the address of the buyer.
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// asset_id is the ID of the data asset to buy shares of.
	AssetId string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// amount is the coin amount to spend on shares.
	Amount types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount"`
	// min_shares_out is the minimum shares the buyer expects (slippage protection).
	// If the bonding curve would mint fewer than this, the tx is rejected.
	// Optional: set to "0" or omit to disable.
	MinSharesOut *cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=min_shares_out,json=minSharesOut,proto3,customtype=cosmossdk.io/math.Int" json:"min_shares_out,omitempty"`
}

func (m *MsgBuyShares) Reset()         { *m = MsgBuyShares{} }
func (m *MsgBuyShares) String() string { return proto.CompactTextString(m) }
func (*MsgBuyShares) ProtoMessage()    {}
func (*MsgBuyShares) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4554f457b53c7be, []int{2}
}
func (m *MsgBuyShares) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyShares) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyShares.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyShares) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyShares.Merge(m, src)
}
func (m *MsgBuyShares) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyShares) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyShares.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyShares proto.InternalMessageInfo

func (m *MsgBuyShares) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgBuyShares) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *MsgBuyShares) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// MsgBuySharesResponse is the response for MsgBuyShares.
type MsgBuySharesResponse struct {
	// shares_purchased is the number of shares acquired.
	SharesPurchased cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=shares_purchased,json=sharesPurchased,proto3,customtype=cosmossdk.io/math.Int" json:"shares_purchased"`
}

func (m *MsgBuySharesResponse) Reset()         { *m = MsgBuySharesResponse{} }
func (m *MsgBuySharesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBuySharesResponse) ProtoMessage()    {}
func (*MsgBuySharesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4554f457b53c7be, []int{3}
}
func (m *MsgBuySharesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuySharesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuySharesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuySharesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuySharesResponse.Merge(m, src)
}
func (m *MsgBuySharesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuySharesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuySharesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuySharesResponse proto.InternalMessageInfo

// MsgFileDispute files a dispute against a data asset.
type MsgFileDispute struct {
	// creator is the address of the plaintiff.
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// asset_id is the ID of the data asset being disputed.
	AssetId string `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// reason is a description of the dispute reason.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// evidence is the raw evidence data.
	Evidence []byte `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
	// requested_remedy is the remedy the plaintiff wants if the dispute is upheld.
	RequestedRemedy DisputeRemedy `protobuf:"varint,5,opt,name=requested_remedy,json=requestedRemedy,proto3,enum=oasyce.datarights.v1.DisputeRemedy" json:"requested_remedy,omitempty"`
}

func (m *MsgFileDispute) Reset()         { *m = MsgFileDispute{} }
func (m *MsgFileDispute) String() string { return proto.CompactTextString(m) }
func (*MsgFileDispute) ProtoMessage()    {}
func (*MsgFileDispute) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4554f457b53c7be, []int{4}
}
func (m *MsgFileDispute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFileDispute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFileDispute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFileDispute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFileDispute.Merge(m, src)
}
func (m *MsgFileDispute) XXX_Size() int {
	return m.Size()
}
func (m *MsgFileDispute) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFileDispute.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFileDispute proto.InternalMessageInfo

func (m *MsgFileDispute) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgFileDispute) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *MsgFileDispute) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *MsgFileDispute) GetEvidence() []byte {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *MsgFileDispute) GetRequestedRemedy() DisputeRemedy {
	if m != nil {
		return m.RequestedRemedy
	}
	return DISPUTE_REMEDY_UNSPECIFIED
}

// MsgFileDisputeResponse is the response for MsgFileDispute.
type MsgFileDisputeResponse struct {
	// dispute_id is the unique identifier of the created dispute.
	DisputeId string `protobuf:"bytes,1,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
}

func (m *MsgFileDisputeResponse) Reset()         { *m = MsgFileDisputeResponse{} }
func (m *MsgFileDisputeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFileDisputeResponse) ProtoMessage()    {}
func (*MsgFileDisputeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4554f457b53c7be, []int{5}
}
func (m *MsgFileDisputeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFileDisputeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFileDisputeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFileDisputeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFileDisputeResponse.Merge(m, src)
}
func (m *MsgFileDisputeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFileDisputeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFileDisputeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFileDisputeResponse proto.InternalMessageInfo

func (m *MsgFileDisputeResponse) GetDisputeId() string {
	if m != nil {
		return m.DisputeId
	}
	return ""
}

// MsgResolveDispute resolves an open dispute.
type MsgResolveDispute struct {
	// creator is the address of the arbitrator resolving the dispute.
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// dispute_id is the ID of the dispute to resolve.
	DisputeId string `protobuf:"bytes,2,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	// remedy is the chosen dispute remedy.
	Remedy DisputeRemedy `protobuf:"varint,3,opt,name=remedy,proto3,enum=oasyce.datarights.v1.DisputeRemedy" json:"remedy,omitempty"`
	// details contains additional resolution details.
	Details []byte `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
}

func (m *MsgResolveDispute) Reset()         { *m = MsgResolveDispute{} }
func (m *MsgResolveDispute) String() string { return proto.CompactTextString(m) }
func (*MsgResolveDispute) ProtoMessage()    {}
func (*MsgResolveDispute) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4554f457b53c7be, []int{6}
}
func (m *MsgResolveDispute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResolveDispute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResolveDispute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResolveDispute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResolveDispute.Merge(m, src)
}
func (m *MsgResolveDispute) XXX_Size() int {
	return m.Size()
}
func (m *MsgResolveDispute) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResolveDispute.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResolveDispute proto.InternalMessageInfo

func (m *MsgResolveDispute) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgResolveDispute) GetDisputeId() string {
	if m != nil {
		return m.DisputeId
	}
	return ""
}

func (m *MsgResolveDispute) GetRemedy() DisputeRemedy {
	if m != nil {
		return m.Remedy
	}
	return DISPUTE_REMEDY_UNSPECIFIED
}

func (m *MsgResolveDispute) GetDetails() []byte {
	if m != nil {
		return m.Details
	}
	return nil
}

// MsgResolveDisputeResponse is the response for MsgResolveDispute.
type MsgResolveDisputeResponse struct {
}

func (m *MsgResolveDisputeResponse) Reset()         { *m = MsgResolveDisputeResponse{} }
func (m *MsgResolveDisputeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResolveDisputeResponse) ProtoMessage()    {}
func (*MsgResolveDisputeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4554f457b53c7be, []int{7}
}
func (m *MsgResolveDisputeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResolveDisputeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResolveDisputeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResolveDisputeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResolveDisputeResponse.Merge(m, src)
}
func (m *MsgResolveDisputeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgResolveDisputeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResolveDisputeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResolveDisputeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterDataAsset)(nil), "oasyce.datarights.v1.MsgRegisterDataAsset")
	proto.RegisterType((*MsgRegisterDataAssetResponse)(nil), "oasyce.datarights.v1.MsgRegisterDataAssetResponse")
	proto.RegisterType((*MsgBuyShares)(nil), "oasyce.datarights.v1.MsgBuyShares")
	proto.RegisterType((*MsgBuySharesResponse)(nil), "oasyce.datarights.v1.MsgBuySharesResponse")
	proto.RegisterType((*MsgFileDispute)(nil), "oasyce.datarights.v1.MsgFileDispute")
	proto.RegisterType((*MsgFileDisputeResponse)(nil), "oasyce.datarights.v1.MsgFileDisputeResponse")
	proto.RegisterType((*MsgResolveDispute)(nil), "oasyce.datarights.v1.MsgResolveDispute")
	proto.RegisterType((*MsgResolveDisputeResponse)(nil), "oasyce.datarights.v1.MsgResolveDisputeResponse")
}

func init() { proto.RegisterFile("oasyce/datarights/v1/tx.proto", fileDescriptor_f4554f457b53c7be) }

var fileDescriptor_f4554f457b53c7be = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xbf, 0x6f, 0x23, 0x45,
	0x14, 0xf6, 0xda, 0xb9, 0xe4, 0xf2, 0x1c, 0xe5, 0x2e, 0xa3, 0x70, 0x6c, 0x0c, 0xe7, 0x98, 0x3d,
	0x04, 0x91, 0xe1, 0x76, 0x65, 0x83, 0x14, 0x11, 0xaa, 0x38, 0xd1, 0x89, 0x14, 0xe1, 0xc7, 0x1e,
	0xa2, 0x80, 0xc2, 0x9a, 0xec, 0x8e, 0x76, 0x07, 0xb2, 0x33, 0x66, 0xdf, 0xd8, 0x3a, 0x77, 0x88,
	0x92, 0x8a, 0x8a, 0x82, 0xff, 0x01, 0x29, 0xc5, 0xfd, 0x11, 0x29, 0x4f, 0x57, 0x21, 0x8a, 0x08,
	0x25, 0x45, 0xfe, 0x00, 0x4a, 0x1a, 0xb4, 0xb3, 0xe3, 0x8d, 0xe3, 0x6c, 0xc0, 0x02, 0x1a, 0x6b,
	0xde, 0xf7, 0xbe, 0x79, 0xf3, 0xf9, 0x7b, 0x6f, 0x66, 0xe1, 0xa1, 0xa4, 0x38, 0x0e, 0x98, 0x17,
	0x52, 0x45, 0x53, 0x1e, 0xc5, 0x0a, 0xbd, 0x51, 0xc7, 0x53, 0xcf, 0xdc, 0x41, 0x2a, 0x95, 0x24,
	0xeb, 0x79, 0xda, 0xbd, 0x4a, 0xbb, 0xa3, 0x4e, 0xa3, 0x19, 0x48, 0x4c, 0x24, 0x7a, 0x47, 0x14,
	0x99, 0x37, 0xea, 0x1c, 0x31, 0x45, 0x3b, 0x5e, 0x20, 0xb9, 0xc8, 0x77, 0x35, 0x5e, 0x35, 0xf9,
	0x04, 0xa3, 0xac, 0x5a, 0x82, 0x91, 0x49, 0x6c, 0xe4, 0x89, 0xbe, 0x8e, 0xbc, 0x3c, 0x30, 0xa9,
	0xf5, 0x48, 0x46, 0x32, 0xc7, 0xb3, 0x95, 0x41, 0xd7, 0x68, 0xc2, 0x85, 0xf4, 0xf4, 0xaf, 0x81,
	0x5a, 0xe5, 0x8a, 0xc7, 0x03, 0x66, 0x4a, 0x39, 0x7f, 0x56, 0x61, 0xfd, 0x10, 0x23, 0x9f, 0x45,
	0x1c, 0x15, 0x4b, 0xf7, 0xa9, 0xa2, 0xbb, 0x88, 0x4c, 0x91, 0x2e, 0x2c, 0x05, 0x29, 0xa3, 0x4a,
	0xa6, 0xb6, 0xd5, 0xb2, 0xb6, 0x96, 0x7b, 0xf6, 0xcb, 0xe7, 0x8f, 0xd7, 0x8d, 0x8c, 0xdd, 0x30,
	0x4c, 0x19, 0xe2, 0x53, 0x95, 0x72, 0x11, 0xf9, 0x13, 0x22, 0x21, 0xb0, 0x20, 0x68, 0xc2, 0xec,
	0x6a, 0xb6, 0xc1, 0xd7, 0x6b, 0xd2, 0x82, 0x7a, 0xc8, 0x30, 0x48, 0xf9, 0x40, 0x71, 0x29, 0xec,
	0x9a, 0x4e, 0x4d, 0x43, 0xe4, 0x0d, 0x58, 0x09, 0xa4, 0x50, 0x4c, 0xa8, 0x7e, 0x4c, 0x31, 0xb6,
	0x17, 0x72, 0x8a, 0xc1, 0x3e, 0xa2, 0x18, 0x93, 0x5d, 0xa8, 0xe7, 0xf2, 0xfb, 0x99, 0x76, 0xfb,
	0x4e, 0xcb, 0xda, 0x5a, 0xed, 0xb6, 0xdc, 0x32, 0xc3, 0x5d, 0x5f, 0xaf, 0x3e, 0x1f, 0x0f, 0x98,
	0x0f, 0x69, 0xb1, 0xce, 0xb4, 0x29, 0x1a, 0xa1, 0xbd, 0xd8, 0xaa, 0x65, 0xda, 0xb2, 0x35, 0x79,
	0x02, 0xf5, 0x40, 0xf6, 0x8d, 0x7a, 0xb4, 0x97, 0x5a, 0xb5, 0xad, 0x7a, 0x77, 0xb3, 0xbc, 0xec,
	0x9e, 0xdc, 0xcb, 0x79, 0xbd, 0x85, 0xd3, 0xb3, 0xcd, 0x8a, 0x0f, 0xc1, 0x04, 0xc0, 0x9d, 0xed,
	0xef, 0x2f, 0x4f, 0xda, 0x13, 0x17, 0x7e, 0xb8, 0x3c, 0x69, 0xbf, 0x75, 0xd3, 0xf7, 0x32, 0x93,
	0x9d, 0x0f, 0xe0, 0xf5, 0x32, 0xdc, 0x67, 0x38, 0x90, 0x02, 0x19, 0xd9, 0x80, 0xbb, 0x34, 0x03,
	0xfa, 0x3c, 0xcc, 0xbb, 0xe0, 0x2f, 0xe9, 0xf8, 0x20, 0x74, 0x7e, 0xae, 0xc2, 0xca, 0x21, 0x46,
	0xbd, 0xe1, 0xf8, 0x69, 0x4c, 0x53, 0x86, 0xff, 0xaa, 0x61, 0xd3, 0xf5, 0xab, 0xd7, 0xea, 0x93,
	0x6d, 0x58, 0xa4, 0x89, 0x1c, 0x0a, 0xa5, 0x5b, 0x56, 0xef, 0x6e, 0xb8, 0xa6, 0x54, 0x36, 0xc8,
	0xae, 0x19, 0x64, 0x77, 0x4f, 0x72, 0x61, 0x0c, 0x31, 0x74, 0xf2, 0x19, 0xac, 0x26, 0x5c, 0xf4,
	0x51, 0xab, 0xea, 0xcb, 0xa1, 0xca, 0x1b, 0xda, 0x7b, 0xe7, 0xf4, 0x6c, 0xd3, 0xfa, 0xed, 0x6c,
	0xf3, 0x95, 0xbc, 0x0e, 0x86, 0xdf, 0xb8, 0x5c, 0x7a, 0x09, 0x55, 0xb1, 0x7b, 0x20, 0xd4, 0xcb,
	0xe7, 0x8f, 0xc1, 0x1c, 0x70, 0x20, 0x94, 0xbf, 0x92, 0x70, 0x91, 0xff, 0xaf, 0x4f, 0x86, 0x6a,
	0xc7, 0x9b, 0xf5, 0xb7, 0x59, 0xea, 0x6f, 0xe1, 0x85, 0x23, 0xf4, 0x50, 0x17, 0x71, 0xe1, 0xe7,
	0x17, 0x70, 0xdf, 0xe8, 0x1a, 0x0c, 0xd3, 0x20, 0xa6, 0xc8, 0x8c, 0xaf, 0x5a, 0x5d, 0x65, 0x5e,
	0x75, 0xf7, 0xf2, 0x22, 0x9f, 0x4e, 0x6a, 0x38, 0x3f, 0x55, 0x61, 0xf5, 0x10, 0xa3, 0x27, 0xfc,
	0x98, 0xed, 0x73, 0x1c, 0x0c, 0x15, 0xfb, 0xbf, 0xdb, 0xf1, 0x00, 0x16, 0x53, 0x46, 0xb1, 0xb8,
	0x41, 0x26, 0x22, 0x0d, 0xb8, 0xcb, 0x46, 0x3c, 0x64, 0x22, 0x60, 0xda, 0xe7, 0x15, 0xbf, 0x88,
	0xc9, 0xc7, 0x70, 0x3f, 0x65, 0xdf, 0x0e, 0x19, 0x2a, 0x16, 0xf6, 0x53, 0x96, 0xb0, 0x70, 0x6c,
	0xae, 0xce, 0xa3, 0xf2, 0x19, 0x37, 0xda, 0x7d, 0x4d, 0xf5, 0xef, 0x15, 0x9b, 0x73, 0x60, 0xa7,
	0x33, 0xdb, 0x86, 0x56, 0x69, 0x1b, 0xa6, 0x5c, 0x70, 0xb6, 0xe1, 0xc1, 0x75, 0xa4, 0x68, 0xc5,
	0x43, 0x80, 0x30, 0x87, 0xae, 0x86, 0x7b, 0xd9, 0x20, 0x07, 0xa1, 0xf3, 0x87, 0x05, 0x6b, 0xfa,
	0x6a, 0xa0, 0x3c, 0x1e, 0xfd, 0x27, 0x53, 0xaf, 0x1f, 0x54, 0x9d, 0x39, 0x88, 0x7c, 0x98, 0x19,
	0xab, 0xad, 0xa9, 0xcd, 0x6f, 0x8d, 0xd9, 0x42, 0x6c, 0x58, 0x0a, 0x99, 0xa2, 0xfc, 0x18, 0x8d,
	0xf9, 0x93, 0x70, 0xe7, 0xfd, 0x59, 0xaf, 0x1e, 0xdd, 0xf2, 0x24, 0x4c, 0xff, 0x3f, 0xe7, 0x35,
	0xd8, 0xb8, 0x01, 0x4e, 0x1c, 0xeb, 0xfe, 0x52, 0x83, 0xda, 0x21, 0x46, 0x04, 0x61, 0xed, 0xe6,
	0x73, 0xdd, 0x2e, 0x97, 0x5d, 0xf6, 0xba, 0x34, 0xba, 0xf3, 0x73, 0x8b, 0x76, 0x7d, 0x05, 0xcb,
	0x57, 0x4f, 0x8d, 0x73, 0x6b, 0x81, 0x82, 0xd3, 0x68, 0xff, 0x33, 0xa7, 0x28, 0x4e, 0xa1, 0x3e,
	0x7d, 0x75, 0xde, 0xbc, 0x75, 0xeb, 0x14, 0xab, 0xf1, 0xee, 0x3c, 0xac, 0xe2, 0x88, 0xaf, 0x61,
	0x75, 0x66, 0x96, 0xde, 0xfe, 0x1b, 0x17, 0xa6, 0x89, 0x0d, 0x6f, 0x4e, 0xe2, 0xe4, 0xac, 0xc6,
	0x9d, 0xef, 0x2e, 0x4f, 0xda, 0x56, 0x6f, 0xff, 0xf4, 0xbc, 0x69, 0xbd, 0x38, 0x6f, 0x5a, 0xbf,
	0x9f, 0x37, 0xad, 0x1f, 0x2f, 0x9a, 0x95, 0x17, 0x17, 0xcd, 0xca, 0xaf, 0x17, 0xcd, 0xca, 0x97,
	0xed, 0x88, 0xab, 0x78, 0x78, 0xe4, 0x06, 0x32, 0xf1, 0xcc, 0x58, 0x04, 0x31, 0xe5, 0xc2, 0x7b,
	0x36, 0x3d, 0x1e, 0xfa, 0x33, 0x7d, 0xb4, 0xa8, 0xbf, 0xd3, 0xef, 0xfd, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xaf, 0x41, 0x87, 0x35, 0x7d, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterDataAsset registers a new data asset on-chain.
	RegisterDataAsset(ctx context.Context, in *MsgRegisterDataAsset, opts ...grpc.CallOption) (*MsgRegisterDataAssetResponse, error)
	// BuyShares purchases shares of a data asset via bonding curve.
	BuyShares(ctx context.Context, in *MsgBuyShares, opts ...grpc.CallOption) (*MsgBuySharesResponse, error)
	// FileDispute files a dispute against a data asset.
	FileDispute(ctx context.Context, in *MsgFileDispute, opts ...grpc.CallOption) (*MsgFileDisputeResponse, error)
	// ResolveDispute resolves an open dispute (arbitrator only).
	ResolveDispute(ctx context.Context, in *MsgResolveDispute, opts ...grpc.CallOption) (*MsgResolveDisputeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterDataAsset(ctx context.Context, in *MsgRegisterDataAsset, opts ...grpc.CallOption) (*MsgRegisterDataAssetResponse, error) {
	out := new(MsgRegisterDataAssetResponse)
	err := c.cc.Invoke(ctx, "/oasyce.datarights.v1.Msg/RegisterDataAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BuyShares(ctx context.Context, in *MsgBuyShares, opts ...grpc.CallOption) (*MsgBuySharesResponse, error) {
	out := new(MsgBuySharesResponse)
	err := c.cc.Invoke(ctx, "/oasyce.datarights.v1.Msg/BuyShares", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FileDispute(ctx context.Context, in *MsgFileDispute, opts ...grpc.CallOption) (*MsgFileDisputeResponse, error) {
	out := new(MsgFileDisputeResponse)
	err := c.cc.Invoke(ctx, "/oasyce.datarights.v1.Msg/FileDispute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ResolveDispute(ctx context.Context, in *MsgResolveDispute, opts ...grpc.CallOption) (*MsgResolveDisputeResponse, error) {
	out := new(MsgResolveDisputeResponse)
	err := c.cc.Invoke(ctx, "/oasyce.datarights.v1.Msg/ResolveDispute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterDataAsset registers a new data asset on-chain.
	RegisterDataAsset(context.Context, *MsgRegisterDataAsset) (*MsgRegisterDataAssetResponse, error)
	// BuyShares purchases shares of a data asset via bonding curve.
	BuyShares(context.Context, *MsgBuyShares) (*MsgBuySharesResponse, error)
	// FileDispute files a dispute against a data asset.
	FileDispute(context.Context, *MsgFileDispute) (*MsgFileDisputeResponse, error)
	// ResolveDispute resolves an open dispute (arbitrator only).
	ResolveDispute(context.Context, *MsgResolveDispute) (*MsgResolveDisputeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterDataAsset(ctx context.Context, req *MsgRegisterDataAsset) (*MsgRegisterDataAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDataAsset not implemented")
}
func (*UnimplementedMsgServer) BuyShares(ctx context.Context, req *MsgBuyShares) (*MsgBuySharesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyShares not implemented")
}
func (*UnimplementedMsgServer) FileDispute(ctx context.Context, req *MsgFileDispute) (*MsgFileDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileDispute not implemented")
}
func (*UnimplementedMsgServer) ResolveDispute(ctx context.Context, req *MsgResolveDispute) (*MsgResolveDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveDispute not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterDataAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterDataAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterDataAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.datarights.v1.Msg/RegisterDataAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterDataAsset(ctx, req.(*MsgRegisterDataAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BuyShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBuyShares)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BuyShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.datarights.v1.Msg/BuyShares",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BuyShares(ctx, req.(*MsgBuyShares))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FileDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFileDispute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FileDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.datarights.v1.Msg/FileDispute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FileDispute(ctx, req.(*MsgFileDispute))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ResolveDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgResolveDispute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ResolveDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.datarights.v1.Msg/ResolveDispute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ResolveDispute(ctx, req.(*MsgResolveDispute))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oasyce.datarights.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDataAsset",
			Handler:    _Msg_RegisterDataAsset_Handler,
		},
		{
			MethodName: "BuyShares",
			Handler:    _Msg_BuyShares_Handler,
		},
		{
			MethodName: "FileDispute",
			Handler:    _Msg_FileDispute_Handler,
		},
		{
			MethodName: "ResolveDispute",
			Handler:    _Msg_ResolveDispute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oasyce/datarights/v1/tx.proto",
}

func (m *MsgRegisterDataAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDataAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDataAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CoCreators) > 0 {
		for iNdEx := len(m.CoCreators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CoCreators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Tags) > 0 {
		for iNdEx := len(m.Tags) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Tags[iNdEx])
			copy(dAtA[i:], m.Tags[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Tags[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.RightsType != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RightsType))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterDataAssetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDataAssetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDataAssetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuyShares) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyShares) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyShares) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinSharesOut != nil {
		{
			size := m.MinSharesOut.Size()
			i -= size
			if _, err := m.MinSharesOut.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuySharesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuySharesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuySharesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SharesPurchased.Size()
		i -= size
		if _, err := m.SharesPurchased.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgFileDispute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFileDispute) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFileDispute) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestedRemedy != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestedRemedy))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Evidence) > 0 {
		i -= len(m.Evidence)
		copy(dAtA[i:], m.Evidence)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Evidence)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFileDisputeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFileDisputeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFileDisputeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DisputeId) > 0 {
		i -= len(m.DisputeId)
		copy(dAtA[i:], m.DisputeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DisputeId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgResolveDispute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResolveDispute) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResolveDispute) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Details) > 0 {
		i -= len(m.Details)
		copy(dAtA[i:], m.Details)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Details)))
		i--
		dAtA[i] = 0x22
	}
	if m.Remedy != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Remedy))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DisputeId) > 0 {
		i -= len(m.DisputeId)
		copy(dAtA[i:], m.DisputeId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DisputeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgResolveDisputeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResolveDisputeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResolveDisputeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterDataAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContentHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RightsType != 0 {
		n += 1 + sovTx(uint64(m.RightsType))
	}
	if len(m.Tags) > 0 {
		for _, s := range m.Tags {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.CoCreators) > 0 {
		for _, e := range m.CoCreators {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgRegisterDataAssetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBuyShares) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.MinSharesOut != nil {
		l = m.MinSharesOut.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBuySharesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SharesPurchased.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgFileDispute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Evidence)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RequestedRemedy != 0 {
		n += 1 + sovTx(uint64(m.RequestedRemedy))
	}
	return n
}

func (m *MsgFileDisputeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DisputeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgResolveDispute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DisputeId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Remedy != 0 {
		n += 1 + sovTx(uint64(m.Remedy))
	}
	l = len(m.Details)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgResolveDisputeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterDataAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDataAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDataAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RightsType", wireType)
			}
			m.RightsType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RightsType |= RightsType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoCreators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CoCreators = append(m.CoCreators, CoCreator{})
			if err := m.CoCreators[len(m.CoCreators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterDataAssetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDataAssetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDataAssetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyShares) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyShares: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyShares: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSharesOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v cosmossdk_io_math.Int
			m.MinSharesOut = &v
			if err := m.MinSharesOut.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuySharesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuySharesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuySharesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SharesPurchased", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SharesPurchased.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFileDispute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFileDispute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFileDispute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Evidence = append(m.Evidence[:0], dAtA[iNdEx:postIndex]...)
			if m.Evidence == nil {
				m.Evidence = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestedRemedy", wireType)
			}
			m.RequestedRemedy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestedRemedy |= DisputeRemedy(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFileDisputeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFileDisputeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFileDisputeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisputeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResolveDispute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResolveDispute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResolveDispute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisputeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remedy", wireType)
			}
			m.Remedy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Remedy |= DisputeRemedy(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Details = append(m.Details[:0], dAtA[iNdEx:postIndex]...)
			if m.Details == nil {
				m.Details = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResolveDisputeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResolveDisputeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResolveDisputeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
