// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/anchor/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion3

// MsgAnchorTrace anchors a single trace record on-chain.
type MsgAnchorTrace struct {
	Signer         string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	TraceId        []byte `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	NodePubkey     []byte `protobuf:"bytes,3,opt,name=node_pubkey,json=nodePubkey,proto3" json:"node_pubkey,omitempty"`
	Capability     string `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`
	Outcome        uint32 `protobuf:"varint,5,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Timestamp      uint64 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TraceSignature []byte `protobuf:"bytes,7,opt,name=trace_signature,json=traceSignature,proto3" json:"trace_signature,omitempty"`
}

func (m *MsgAnchorTrace) Reset()         { *m = MsgAnchorTrace{} }
func (m *MsgAnchorTrace) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorTrace) ProtoMessage()    {}
func (*MsgAnchorTrace) Descriptor() ([]byte, []int) {
	return fileDescriptor_anchor_tx, []int{0}
}
func (m *MsgAnchorTrace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAnchorTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAnchorTrace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAnchorTrace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorTrace.Merge(m, src)
}
func (m *MsgAnchorTrace) XXX_Size() int {
	return m.Size()
}
func (m *MsgAnchorTrace) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorTrace.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorTrace proto.InternalMessageInfo

func (m *MsgAnchorTrace) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgAnchorTrace) GetTraceId() []byte {
	if m != nil {
		return m.TraceId
	}
	return nil
}

func (m *MsgAnchorTrace) GetNodePubkey() []byte {
	if m != nil {
		return m.NodePubkey
	}
	return nil
}

func (m *MsgAnchorTrace) GetCapability() string {
	if m != nil {
		return m.Capability
	}
	return ""
}

func (m *MsgAnchorTrace) GetOutcome() uint32 {
	if m != nil {
		return m.Outcome
	}
	return 0
}

func (m *MsgAnchorTrace) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MsgAnchorTrace) GetTraceSignature() []byte {
	if m != nil {
		return m.TraceSignature
	}
	return nil
}

// MsgAnchorTraceResponse is the response for MsgAnchorTrace.
type MsgAnchorTraceResponse struct{}

func (m *MsgAnchorTraceResponse) Reset()         { *m = MsgAnchorTraceResponse{} }
func (m *MsgAnchorTraceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorTraceResponse) ProtoMessage()    {}
func (*MsgAnchorTraceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_anchor_tx, []int{1}
}
func (m *MsgAnchorTraceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAnchorTraceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return []byte{}, nil
}
func (m *MsgAnchorTraceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorTraceResponse.Merge(m, src)
}
func (m *MsgAnchorTraceResponse) XXX_Size() int {
	return 0
}
func (m *MsgAnchorTraceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorTraceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorTraceResponse proto.InternalMessageInfo

// MsgAnchorBatch anchors multiple traces in a single transaction.
type MsgAnchorBatch struct {
	Signer  string            `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Anchors []*MsgAnchorTrace `protobuf:"bytes,2,rep,name=anchors,proto3" json:"anchors,omitempty"`
}

func (m *MsgAnchorBatch) Reset()         { *m = MsgAnchorBatch{} }
func (m *MsgAnchorBatch) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorBatch) ProtoMessage()    {}
func (*MsgAnchorBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_anchor_tx, []int{2}
}
func (m *MsgAnchorBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAnchorBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAnchorBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAnchorBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorBatch.Merge(m, src)
}
func (m *MsgAnchorBatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgAnchorBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorBatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorBatch proto.InternalMessageInfo

func (m *MsgAnchorBatch) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgAnchorBatch) GetAnchors() []*MsgAnchorTrace {
	if m != nil {
		return m.Anchors
	}
	return nil
}

// MsgAnchorBatchResponse is the response for MsgAnchorBatch.
type MsgAnchorBatchResponse struct {
	Anchored uint32 `protobuf:"varint,1,opt,name=anchored,proto3" json:"anchored,omitempty"`
	Skipped  uint32 `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
}

func (m *MsgAnchorBatchResponse) Reset()         { *m = MsgAnchorBatchResponse{} }
func (m *MsgAnchorBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAnchorBatchResponse) ProtoMessage()    {}
func (*MsgAnchorBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_anchor_tx, []int{3}
}
func (m *MsgAnchorBatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAnchorBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAnchorBatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAnchorBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAnchorBatchResponse.Merge(m, src)
}
func (m *MsgAnchorBatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAnchorBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAnchorBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAnchorBatchResponse proto.InternalMessageInfo

func (m *MsgAnchorBatchResponse) GetAnchored() uint32 {
	if m != nil {
		return m.Anchored
	}
	return 0
}

func (m *MsgAnchorBatchResponse) GetSkipped() uint32 {
	if m != nil {
		return m.Skipped
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgAnchorTrace)(nil), "oasyce.anchor.v1.MsgAnchorTrace")
	proto.RegisterType((*MsgAnchorTraceResponse)(nil), "oasyce.anchor.v1.MsgAnchorTraceResponse")
	proto.RegisterType((*MsgAnchorBatch)(nil), "oasyce.anchor.v1.MsgAnchorBatch")
	proto.RegisterType((*MsgAnchorBatchResponse)(nil), "oasyce.anchor.v1.MsgAnchorBatchResponse")
}

func init() { proto.RegisterFile("oasyce/anchor/v1/tx.proto", fileDescriptor_anchor_tx) }

var fileDescriptor_anchor_tx = []byte{
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0x8c, 0x93, 0x41, 0x6e, 0xe2, 0x30,
	0x18, 0x85, 0x65, 0x60, 0x60, 0xf8, 0x19, 0x66, 0x90, 0x35, 0x83, 0x0c, 0x33, 0x42, 0x51, 0xa4,
	0x91, 0xb2, 0x32, 0x82, 0xee, 0x58, 0x20, 0xb5, 0x7b, 0xba, 0x88, 0xba, 0xe9, 0x0a, 0x19, 0x63,
	0x85, 0x88, 0x26, 0x8e, 0x62, 0x13, 0x95, 0x33, 0x74, 0xd1, 0xfb, 0x70, 0x95, 0x5e, 0xa6, 0x8a,
	0x4d, 0x68, 0x88, 0x54, 0xe8, 0xf2, 0xbd, 0xdf, 0x3c, 0x7f, 0xff, 0x33, 0x81, 0x81, 0x64, 0x6a,
	0xcf, 0xc5, 0x98, 0xc5, 0x7c, 0x23, 0xd3, 0x71, 0x36, 0x19, 0xeb, 0x67, 0x9a, 0xa4, 0x52, 0x4b,
	0xdc, 0xb3, 0x23, 0x6a, 0x47, 0x34, 0x9b, 0xb8, 0xaf, 0x35, 0xf8, 0xb9, 0x50, 0xc1, 0xad, 0x31,
	0x1e, 0x52, 0xc6, 0x05, 0xee, 0x43, 0x53, 0x85, 0x41, 0x2c, 0x52, 0x82, 0x1c, 0xe4, 0xb5, 0xfd,
	0xa3, 0xc2, 0x43, 0xf8, 0xae, 0xf3, 0x03, 0xcb, 0x70, 0x4d, 0x6a, 0x0e, 0xf2, 0x7e, 0xf8, 0x27,
	0x8d, 0x1d, 0xe8, 0xc4, 0x72, 0x2d, 0x96, 0xc9, 0x6e, 0xb5, 0x15, 0x7b, 0x52, 0x37, 0xe3, 0xb2,
	0x85, 0x47, 0x00, 0x9c, 0x25, 0x6c, 0x15, 0x3e, 0x85, 0x7a, 0x4f, 0x1a, 0x26, 0xb9, 0xe4, 0x60,
	0x02, 0x2d, 0xb9, 0xd3, 0x5c, 0x46, 0x82, 0x7c, 0x73, 0x90, 0xd7, 0xf5, 0x0b, 0x89, 0xff, 0x41,
	0x5b, 0x87, 0x91, 0x50, 0x9a, 0x45, 0x09, 0x69, 0x3a, 0xc8, 0x6b, 0xf8, 0x1f, 0x06, 0xf6, 0xe0,
	0x97, 0xa5, 0xc8, 0x29, 0x99, 0xde, 0xa5, 0x82, 0xb4, 0xcc, 0xed, 0x55, 0x7b, 0xf6, 0xff, 0x30,
	0x77, 0x31, 0x81, 0xdf, 0x5c, 0xaa, 0x48, 0x2a, 0x1a, 0xa9, 0x80, 0x66, 0x13, 0x6a, 0x97, 0xeb,
	0xa1, 0xd9, 0x71, 0x4d, 0x97, 0x40, 0xff, 0xbc, 0x10, 0x5f, 0xa8, 0x44, 0xc6, 0x4a, 0xb8, 0x2f,
	0xa8, 0xd4, 0xd5, 0x1d, 0xd3, 0x7c, 0xf3, 0x69, 0x57, 0x33, 0x68, 0xd9, 0x8e, 0x15, 0xa9, 0x39,
	0x75, 0xaf, 0x33, 0x75, 0x68, 0xb5, 0x7a, 0x5a, 0xb9, 0xa5, 0xf8, 0xc1, 0x57, 0x39, 0xef, 0x4b,
	0x9c, 0x06, 0xa6, 0xe0, 0xcc, 0x1f, 0xca, 0x66, 0x89, 0xb5, 0xc1, 0xea, 0xfa, 0x27, 0x9d, 0xd7,
	0xac, 0xb6, 0x61, 0x92, 0x08, 0xfb, 0x86, 0x5d, 0xbf, 0x90, 0xd3, 0x37, 0x04, 0xf5, 0x85, 0x0a,
	0xf0, 0x23, 0x74, 0xca, 0xff, 0x86, 0xab, 0xe0, 0x43, 0xef, 0xea, 0x6a, 0x05, 0xd8, 0x29, 0xda,
	0x96, 0x77, 0x29, 0xda, 0x9c, 0xb8, 0x18, 0x7d, 0xb6, 0xf3, 0x70, 0x74, 0x98, 0xff, 0xc5, 0x03,
	0xf8, 0x53, 0x29, 0x4d, 0xa4, 0x59, 0xc8, 0x45, 0x0f, 0xad, 0x9a, 0xe6, 0x03, 0xb8, 0x79, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0x4e, 0x1a, 0x21, 0x6c, 0x1d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
type MsgClient interface {
	AnchorTrace(ctx context.Context, in *MsgAnchorTrace, opts ...grpc.CallOption) (*MsgAnchorTraceResponse, error)
	AnchorBatch(ctx context.Context, in *MsgAnchorBatch, opts ...grpc.CallOption) (*MsgAnchorBatchResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AnchorTrace(ctx context.Context, in *MsgAnchorTrace, opts ...grpc.CallOption) (*MsgAnchorTraceResponse, error) {
	out := new(MsgAnchorTraceResponse)
	err := c.cc.Invoke(ctx, "/oasyce.anchor.v1.Msg/AnchorTrace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AnchorBatch(ctx context.Context, in *MsgAnchorBatch, opts ...grpc.CallOption) (*MsgAnchorBatchResponse, error) {
	out := new(MsgAnchorBatchResponse)
	err := c.cc.Invoke(ctx, "/oasyce.anchor.v1.Msg/AnchorBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AnchorTrace(context.Context, *MsgAnchorTrace) (*MsgAnchorTraceResponse, error)
	AnchorBatch(context.Context, *MsgAnchorBatch) (*MsgAnchorBatchResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct{}

func (*UnimplementedMsgServer) AnchorTrace(ctx context.Context, req *MsgAnchorTrace) (*MsgAnchorTraceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnchorTrace not implemented")
}
func (*UnimplementedMsgServer) AnchorBatch(ctx context.Context, req *MsgAnchorBatch) (*MsgAnchorBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnchorBatch not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AnchorTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAnchorTrace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AnchorTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.anchor.v1.Msg/AnchorTrace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AnchorTrace(ctx, req.(*MsgAnchorTrace))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AnchorBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAnchorBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AnchorBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.anchor.v1.Msg/AnchorBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AnchorBatch(ctx, req.(*MsgAnchorBatch))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oasyce.anchor.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnchorTrace",
			Handler:    _Msg_AnchorTrace_Handler,
		},
		{
			MethodName: "AnchorBatch",
			Handler:    _Msg_AnchorBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oasyce/anchor/v1/tx.proto",
}

// --- Marshal/Unmarshal for MsgAnchorTrace ---

func (m *MsgAnchorTrace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAnchorTrace) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAnchorTrace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TraceSignature) > 0 {
		i -= len(m.TraceSignature)
		copy(dAtA[i:], m.TraceSignature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TraceSignature)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Timestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x30
	}
	if m.Outcome != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Outcome))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Capability) > 0 {
		i -= len(m.Capability)
		copy(dAtA[i:], m.Capability)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Capability)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.NodePubkey) > 0 {
		i -= len(m.NodePubkey)
		copy(dAtA[i:], m.NodePubkey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NodePubkey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TraceId) > 0 {
		i -= len(m.TraceId)
		copy(dAtA[i:], m.TraceId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TraceId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

// MsgAnchorTraceResponse marshal/unmarshal
func (m *MsgAnchorTraceResponse) Marshal() (dAtA []byte, err error) {
	return []byte{}, nil
}
func (m *MsgAnchorTraceResponse) MarshalTo(dAtA []byte) (int, error) {
	return 0, nil
}
func (m *MsgAnchorTraceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	return len(dAtA), nil
}
func (m *MsgAnchorTraceResponse) Size() int { return 0 }
func (m *MsgAnchorTraceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		_ = fieldNum
		wireType := int(wire & 0x7)
		_ = wireType
		iNdEx = preIndex
		skippy, err := skipTx(dAtA[iNdEx:])
		if err != nil {
			return err
		}
		if (skippy < 0) || (iNdEx+skippy) < 0 {
			return ErrInvalidLengthTx
		}
		if (iNdEx + skippy) > l {
			return io.ErrUnexpectedEOF
		}
		iNdEx += skippy
	}
	return nil
}

// --- Marshal/Unmarshal for MsgAnchorBatch ---

func (m *MsgAnchorBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAnchorBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAnchorBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Anchors) > 0 {
		for iNdEx := len(m.Anchors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Anchors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

// MsgAnchorBatchResponse marshal/unmarshal

func (m *MsgAnchorBatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAnchorBatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAnchorBatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Skipped != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Skipped))
		i--
		dAtA[i] = 0x10
	}
	if m.Anchored != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Anchored))
		i--
		dAtA[i] = 0x08
	}
	return len(dAtA) - i, nil
}

// Size methods

func (m *MsgAnchorTrace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TraceId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NodePubkey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Capability)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Outcome != 0 {
		n += 1 + sovTx(uint64(m.Outcome))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTx(uint64(m.Timestamp))
	}
	l = len(m.TraceSignature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAnchorBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Anchors) > 0 {
		for _, e := range m.Anchors {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgAnchorBatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Anchored != 0 {
		n += 1 + sovTx(uint64(m.Anchored))
	}
	if m.Skipped != 0 {
		n += 1 + sovTx(uint64(m.Skipped))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset--
	dAtA[offset] = uint8(v)
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset--
	}
	dAtA[offset] = uint8(v)
	return offset
}

// Unmarshal methods

func (m *MsgAnchorTrace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAnchorTrace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAnchorTrace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1: // signer
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2: // trace_id
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceId = append(m.TraceId[:0], dAtA[iNdEx:postIndex]...)
			if m.TraceId == nil {
				m.TraceId = []byte{}
			}
			iNdEx = postIndex
		case 3: // node_pubkey
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodePubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodePubkey = append(m.NodePubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.NodePubkey == nil {
				m.NodePubkey = []byte{}
			}
			iNdEx = postIndex
		case 4: // capability
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capability", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Capability = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5: // outcome
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outcome", wireType)
			}
			m.Outcome = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Outcome |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6: // timestamp
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7: // trace_signature
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraceSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceSignature = append(m.TraceSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.TraceSignature == nil {
				m.TraceSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *MsgAnchorBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAnchorBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAnchorBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1: // signer
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2: // anchors
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anchors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Anchors = append(m.Anchors, &MsgAnchorTrace{})
			if err := m.Anchors[len(m.Anchors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *MsgAnchorBatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAnchorBatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAnchorBatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1: // anchored
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Anchored", wireType)
			}
			m.Anchored = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Anchored |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2: // skipped
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skipped", wireType)
			}
			m.Skipped = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Skipped |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
