// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/work/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the work module's genesis state.
type GenesisState struct {
	Params      Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Tasks       []Task            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks"`
	Executors   []ExecutorProfile `protobuf:"bytes,3,rep,name=executors,proto3" json:"executors"`
	TaskCounter uint64            `protobuf:"varint,4,opt,name=task_counter,json=taskCounter,proto3" json:"task_counter,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff15df7a3906ae27, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetTasks() []Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *GenesisState) GetExecutors() []ExecutorProfile {
	if m != nil {
		return m.Executors
	}
	return nil
}

func (m *GenesisState) GetTaskCounter() uint64 {
	if m != nil {
		return m.TaskCounter
	}
	return 0
}

// Params defines the governance-tunable parameters for the work module.
type Params struct {
	DefaultRedundancy     uint32                      `protobuf:"varint,1,opt,name=default_redundancy,json=defaultRedundancy,proto3" json:"default_redundancy,omitempty"`
	MinTimeoutBlocks      uint64                      `protobuf:"varint,2,opt,name=min_timeout_blocks,json=minTimeoutBlocks,proto3" json:"min_timeout_blocks,omitempty"`
	MaxTimeoutBlocks      uint64                      `protobuf:"varint,3,opt,name=max_timeout_blocks,json=maxTimeoutBlocks,proto3" json:"max_timeout_blocks,omitempty"`
	RevealBlocks          uint64                      `protobuf:"varint,4,opt,name=reveal_blocks,json=revealBlocks,proto3" json:"reveal_blocks,omitempty"`
	MinBounty             cosmossdk_io_math.Int       `protobuf:"bytes,5,opt,name=min_bounty,json=minBounty,proto3,customtype=cosmossdk.io/math.Int" json:"min_bounty"`
	ExecutorShare         cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=executor_share,json=executorShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"executor_share"`
	ProtocolShare         cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=protocol_share,json=protocolShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"protocol_share"`
	BurnShare             cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=burn_share,json=burnShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"burn_share"`
	SubmitterRebate       cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=submitter_rebate,json=submitterRebate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"submitter_rebate"`
	DepositRate           cosmossdk_io_math.LegacyDec `protobuf:"bytes,10,opt,name=deposit_rate,json=depositRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"deposit_rate"`
	DisputeBondRate       cosmossdk_io_math.LegacyDec `protobuf:"bytes,11,opt,name=dispute_bond_rate,json=disputeBondRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"dispute_bond_rate"`
	MinExecutorReputation uint32                      `protobuf:"varint,12,opt,name=min_executor_reputation,json=minExecutorReputation,proto3" json:"min_executor_reputation,omitempty"`
	MaxTasksPerBlock      uint32                      `protobuf:"varint,13,opt,name=max_tasks_per_block,json=maxTasksPerBlock,proto3" json:"max_tasks_per_block,omitempty"`
	ReputationCapPerEpoch uint32                      `protobuf:"varint,14,opt,name=reputation_cap_per_epoch,json=reputationCapPerEpoch,proto3" json:"reputation_cap_per_epoch,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff15df7a3906ae27, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetDefaultRedundancy() uint32 {
	if m != nil {
		return m.DefaultRedundancy
	}
	return 0
}

func (m *Params) GetMinTimeoutBlocks() uint64 {
	if m != nil {
		return m.MinTimeoutBlocks
	}
	return 0
}

func (m *Params) GetMaxTimeoutBlocks() uint64 {
	if m != nil {
		return m.MaxTimeoutBlocks
	}
	return 0
}

func (m *Params) GetRevealBlocks() uint64 {
	if m != nil {
		return m.RevealBlocks
	}
	return 0
}

func (m *Params) GetMinExecutorReputation() uint32 {
	if m != nil {
		return m.MinExecutorReputation
	}
	return 0
}

func (m *Params) GetMaxTasksPerBlock() uint32 {
	if m != nil {
		return m.MaxTasksPerBlock
	}
	return 0
}

func (m *Params) GetReputationCapPerEpoch() uint32 {
	if m != nil {
		return m.ReputationCapPerEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "oasyce.work.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "oasyce.work.v1.Params")
}

func init() { proto.RegisterFile("oasyce/work/v1/genesis.proto", fileDescriptor_ff15df7a3906ae27) }

var fileDescriptor_ff15df7a3906ae27 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x4f, 0x13, 0x4f,
	0x1c, 0xc6, 0xbb, 0x3f, 0x4a, 0xf9, 0x75, 0xda, 0x22, 0xac, 0xa0, 0x2b, 0x9a, 0xb6, 0xa2, 0x87,
	0x26, 0xca, 0x56, 0xd0, 0x68, 0xe2, 0xc1, 0x43, 0x81, 0x18, 0x8c, 0x87, 0x66, 0xe1, 0x60, 0x8c,
	0x66, 0x33, 0xbb, 0xfb, 0xa5, 0x9d, 0xb4, 0x3b, 0xb3, 0x99, 0x99, 0xc5, 0xf6, 0x5d, 0x78, 0xf4,
	0xe8, 0x8b, 0xf0, 0x1d, 0x78, 0xe1, 0x48, 0x3c, 0x19, 0x0f, 0xc4, 0xc0, 0x1b, 0x31, 0xf3, 0xa7,
	0x45, 0xea, 0xad, 0x37, 0xf8, 0x3e, 0xcf, 0xf3, 0x99, 0x99, 0xed, 0x33, 0x83, 0xee, 0x31, 0x2c,
	0xc6, 0x31, 0xb4, 0x3f, 0x31, 0x3e, 0x68, 0x9f, 0x6c, 0xb7, 0x7b, 0x40, 0x41, 0x10, 0xe1, 0x67,
	0x9c, 0x49, 0xe6, 0x2e, 0x1b, 0xd5, 0x57, 0xaa, 0x7f, 0xb2, 0xbd, 0x71, 0x27, 0x66, 0x22, 0x65,
	0x22, 0xd4, 0x6a, 0xdb, 0xfc, 0x63, 0xac, 0x1b, 0x6b, 0x3d, 0xd6, 0x63, 0x66, 0xae, 0xfe, 0xb2,
	0xd3, 0x8d, 0x19, 0xbc, 0x1c, 0x67, 0x60, 0x13, 0x9b, 0xe7, 0x0e, 0xaa, 0xbe, 0x36, 0xcb, 0x1d,
	0x4a, 0x2c, 0xc1, 0x7d, 0x86, 0x4a, 0x19, 0xe6, 0x38, 0x15, 0x9e, 0xd3, 0x74, 0x5a, 0x95, 0x9d,
	0x5b, 0xfe, 0xf5, 0xe5, 0xfd, 0xae, 0x56, 0x3b, 0xc5, 0xd3, 0xf3, 0x46, 0x21, 0xb0, 0x5e, 0xf7,
	0x09, 0x5a, 0x94, 0x58, 0x0c, 0x84, 0xf7, 0x5f, 0x73, 0xa1, 0x55, 0xd9, 0x59, 0x9b, 0x0d, 0x1d,
	0x61, 0x31, 0xb0, 0x11, 0x63, 0x74, 0x77, 0x51, 0x19, 0x46, 0x10, 0xe7, 0x92, 0x71, 0xe1, 0x2d,
	0xe8, 0x54, 0x63, 0x36, 0xb5, 0x6f, 0x0d, 0x5d, 0xce, 0x8e, 0xc9, 0x10, 0x2c, 0xe0, 0x2a, 0xe7,
	0xde, 0x47, 0x55, 0x45, 0x0b, 0x63, 0x96, 0x53, 0x09, 0xdc, 0x2b, 0x36, 0x9d, 0x56, 0x31, 0xa8,
	0xa8, 0xd9, 0xae, 0x19, 0x6d, 0x7e, 0x5f, 0x42, 0x25, 0xb3, 0x65, 0x77, 0x0b, 0xb9, 0x09, 0x1c,
	0xe3, 0x7c, 0x28, 0x43, 0x0e, 0x49, 0x4e, 0x13, 0x4c, 0xe3, 0xb1, 0x3e, 0x66, 0x2d, 0x58, 0xb5,
	0x4a, 0x30, 0x15, 0xdc, 0xc7, 0xc8, 0x4d, 0x09, 0x0d, 0x25, 0x49, 0x81, 0xe5, 0x32, 0x8c, 0x86,
	0x2c, 0xd6, 0x07, 0x54, 0x4b, 0xac, 0xa4, 0x84, 0x1e, 0x19, 0xa1, 0xa3, 0xe7, 0xda, 0x8d, 0x47,
	0xb3, 0xee, 0x05, 0xeb, 0xc6, 0xa3, 0xeb, 0xee, 0x07, 0xa8, 0xc6, 0xe1, 0x04, 0xf0, 0x70, 0x62,
	0x34, 0x3b, 0xaf, 0x9a, 0xa1, 0x35, 0xbd, 0x41, 0x48, 0x6d, 0x20, 0x52, 0x27, 0x19, 0x7b, 0x8b,
	0x4d, 0xa7, 0x55, 0xee, 0x3c, 0x52, 0x9f, 0xe0, 0xd7, 0x79, 0x63, 0xdd, 0xfc, 0xee, 0x22, 0x19,
	0xf8, 0x84, 0xb5, 0x53, 0x2c, 0xfb, 0xfe, 0x01, 0x95, 0x3f, 0xbe, 0x6d, 0x21, 0x5b, 0x88, 0x03,
	0x2a, 0x83, 0x72, 0x4a, 0x68, 0x47, 0xa7, 0xdd, 0x77, 0x68, 0x79, 0xf2, 0xd9, 0x42, 0xd1, 0xc7,
	0x1c, 0xbc, 0x92, 0xe6, 0x6d, 0x5b, 0xde, 0xdd, 0x7f, 0x79, 0x6f, 0xa1, 0x87, 0xe3, 0xf1, 0x1e,
	0xc4, 0x7f, 0x51, 0xf7, 0x20, 0x0e, 0x6a, 0x13, 0xd0, 0xa1, 0xe2, 0x28, 0xb2, 0xae, 0x52, 0xcc,
	0x86, 0x96, 0xbc, 0x34, 0x37, 0x79, 0x02, 0x32, 0xe4, 0x2e, 0x42, 0x51, 0xce, 0xa9, 0xa5, 0xfe,
	0x3f, 0x2f, 0xb5, 0xac, 0x20, 0x86, 0xf8, 0x01, 0xad, 0x88, 0x3c, 0x4a, 0x89, 0x94, 0xc0, 0x43,
	0x0e, 0x11, 0x96, 0xe0, 0x95, 0xe7, 0xe5, 0xde, 0x98, 0xa2, 0x02, 0x4d, 0x72, 0x8f, 0x50, 0x35,
	0x81, 0x8c, 0x09, 0x22, 0x43, 0xae, 0xc8, 0x68, 0x5e, 0x72, 0xc5, 0x62, 0x02, 0x45, 0xfd, 0x88,
	0x56, 0x13, 0x22, 0xb2, 0x5c, 0x42, 0x18, 0x31, 0x9a, 0x18, 0x74, 0x65, 0xee, 0x4d, 0x5b, 0x56,
	0x87, 0xd1, 0x44, 0xe3, 0x9f, 0xa3, 0xdb, 0xaa, 0x64, 0xd3, 0x72, 0x70, 0xc8, 0x72, 0x89, 0x25,
	0x61, 0xd4, 0xab, 0xea, 0x9b, 0xb1, 0x9e, 0x12, 0x3a, 0xb9, 0x88, 0xc1, 0x54, 0x74, 0xb7, 0xd0,
	0x4d, 0xdd, 0x77, 0x75, 0x99, 0xc3, 0x0c, 0xb8, 0x29, 0xb2, 0x57, 0xd3, 0x19, 0x5d, 0x78, 0xa5,
	0x74, 0x81, 0xeb, 0x32, 0xbb, 0x2f, 0x90, 0x77, 0x45, 0x0e, 0x63, 0x9c, 0xe9, 0x0c, 0x64, 0x2c,
	0xee, 0x7b, 0xcb, 0x66, 0x9d, 0x2b, 0x7d, 0x17, 0x67, 0x5d, 0xe0, 0xfb, 0x4a, 0x7c, 0x59, 0xfc,
	0xf2, 0xb5, 0x51, 0xe8, 0xbc, 0x3a, 0xbd, 0xa8, 0x3b, 0x67, 0x17, 0x75, 0xe7, 0xf7, 0x45, 0xdd,
	0xf9, 0x7c, 0x59, 0x2f, 0x9c, 0x5d, 0xd6, 0x0b, 0x3f, 0x2f, 0xeb, 0x85, 0xf7, 0x0f, 0x7b, 0x44,
	0xf6, 0xf3, 0xc8, 0x8f, 0x59, 0xda, 0xb6, 0xef, 0x5c, 0xdc, 0xc7, 0x84, 0xb6, 0x47, 0xe6, 0xbd,
	0xd3, 0x8f, 0x5d, 0x54, 0xd2, 0xcd, 0x7a, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x66, 0x12,
	0x79, 0x6a, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TaskCounter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TaskCounter))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Executors) > 0 {
		for iNdEx := len(m.Executors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Executors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Tasks) > 0 {
		for iNdEx := len(m.Tasks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tasks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReputationCapPerEpoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ReputationCapPerEpoch))
		i--
		dAtA[i] = 0x70
	}
	if m.MaxTasksPerBlock != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxTasksPerBlock))
		i--
		dAtA[i] = 0x68
	}
	if m.MinExecutorReputation != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinExecutorReputation))
		i--
		dAtA[i] = 0x60
	}
	{
		size := m.DisputeBondRate.Size()
		i -= size
		if _, err := m.DisputeBondRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.DepositRate.Size()
		i -= size
		if _, err := m.DepositRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.SubmitterRebate.Size()
		i -= size
		if _, err := m.SubmitterRebate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.BurnShare.Size()
		i -= size
		if _, err := m.BurnShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.ProtocolShare.Size()
		i -= size
		if _, err := m.ProtocolShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.ExecutorShare.Size()
		i -= size
		if _, err := m.ExecutorShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MinBounty.Size()
		i -= size
		if _, err := m.MinBounty.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.RevealBlocks != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RevealBlocks))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxTimeoutBlocks != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxTimeoutBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.MinTimeoutBlocks != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MinTimeoutBlocks))
		i--
		dAtA[i] = 0x10
	}
	if m.DefaultRedundancy != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DefaultRedundancy))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Tasks) > 0 {
		for _, e := range m.Tasks {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Executors) > 0 {
		for _, e := range m.Executors {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TaskCounter != 0 {
		n += 1 + sovGenesis(uint64(m.TaskCounter))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DefaultRedundancy != 0 {
		n += 1 + sovGenesis(uint64(m.DefaultRedundancy))
	}
	if m.MinTimeoutBlocks != 0 {
		n += 1 + sovGenesis(uint64(m.MinTimeoutBlocks))
	}
	if m.MaxTimeoutBlocks != 0 {
		n += 1 + sovGenesis(uint64(m.MaxTimeoutBlocks))
	}
	if m.RevealBlocks != 0 {
		n += 1 + sovGenesis(uint64(m.RevealBlocks))
	}
	l = m.MinBounty.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ExecutorShare.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ProtocolShare.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.BurnShare.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.SubmitterRebate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.DepositRate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.DisputeBondRate.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.MinExecutorReputation != 0 {
		n += 1 + sovGenesis(uint64(m.MinExecutorReputation))
	}
	if m.MaxTasksPerBlock != 0 {
		n += 1 + sovGenesis(uint64(m.MaxTasksPerBlock))
	}
	if m.ReputationCapPerEpoch != 0 {
		n += 1 + sovGenesis(uint64(m.ReputationCapPerEpoch))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tasks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tasks = append(m.Tasks, Task{})
			if err := m.Tasks[len(m.Tasks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Executors = append(m.Executors, ExecutorProfile{})
			if err := m.Executors[len(m.Executors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskCounter", wireType)
			}
			m.TaskCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultRedundancy", wireType)
			}
			m.DefaultRedundancy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultRedundancy |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinTimeoutBlocks", wireType)
			}
			m.MinTimeoutBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinTimeoutBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTimeoutBlocks", wireType)
			}
			m.MaxTimeoutBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTimeoutBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevealBlocks", wireType)
			}
			m.RevealBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RevealBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBounty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinBounty.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutorShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExecutorShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProtocolShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitterRebate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SubmitterRebate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DepositRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeBondRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DisputeBondRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinExecutorReputation", wireType)
			}
			m.MinExecutorReputation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinExecutorReputation |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTasksPerBlock", wireType)
			}
			m.MaxTasksPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTasksPerBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReputationCapPerEpoch", wireType)
			}
			m.ReputationCapPerEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReputationCapPerEpoch |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
