// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oasyce/onboarding/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryRegistrationRequest is the request for Query/Registration.
type QueryRegistrationRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryRegistrationRequest) Reset()         { *m = QueryRegistrationRequest{} }
func (m *QueryRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationRequest) ProtoMessage()    {}
func (*QueryRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54be95d4d3143d75, []int{0}
}
func (m *QueryRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationRequest.Merge(m, src)
}
func (m *QueryRegistrationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationRequest proto.InternalMessageInfo

func (m *QueryRegistrationRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryRegistrationResponse is the response for Query/Registration.
type QueryRegistrationResponse struct {
	Registration Registration `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration"`
}

func (m *QueryRegistrationResponse) Reset()         { *m = QueryRegistrationResponse{} }
func (m *QueryRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationResponse) ProtoMessage()    {}
func (*QueryRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54be95d4d3143d75, []int{1}
}
func (m *QueryRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationResponse.Merge(m, src)
}
func (m *QueryRegistrationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationResponse proto.InternalMessageInfo

func (m *QueryRegistrationResponse) GetRegistration() Registration {
	if m != nil {
		return m.Registration
	}
	return Registration{}
}

// QueryDebtRequest is the request for Query/Debt.
type QueryDebtRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryDebtRequest) Reset()         { *m = QueryDebtRequest{} }
func (m *QueryDebtRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDebtRequest) ProtoMessage()    {}
func (*QueryDebtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54be95d4d3143d75, []int{2}
}
func (m *QueryDebtRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDebtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDebtRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDebtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDebtRequest.Merge(m, src)
}
func (m *QueryDebtRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDebtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDebtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDebtRequest proto.InternalMessageInfo

func (m *QueryDebtRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryDebtResponse is the response for Query/Debt.
type QueryDebtResponse struct {
	Registration Registration `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration"`
}

func (m *QueryDebtResponse) Reset()         { *m = QueryDebtResponse{} }
func (m *QueryDebtResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDebtResponse) ProtoMessage()    {}
func (*QueryDebtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54be95d4d3143d75, []int{3}
}
func (m *QueryDebtResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDebtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDebtResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDebtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDebtResponse.Merge(m, src)
}
func (m *QueryDebtResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDebtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDebtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDebtResponse proto.InternalMessageInfo

func (m *QueryDebtResponse) GetRegistration() Registration {
	if m != nil {
		return m.Registration
	}
	return Registration{}
}

// QueryOnboardingParamsRequest is the request for Query/OnboardingParams.
type QueryOnboardingParamsRequest struct {
}

func (m *QueryOnboardingParamsRequest) Reset()         { *m = QueryOnboardingParamsRequest{} }
func (m *QueryOnboardingParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOnboardingParamsRequest) ProtoMessage()    {}
func (*QueryOnboardingParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_54be95d4d3143d75, []int{4}
}
func (m *QueryOnboardingParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOnboardingParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOnboardingParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOnboardingParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOnboardingParamsRequest.Merge(m, src)
}
func (m *QueryOnboardingParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOnboardingParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOnboardingParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOnboardingParamsRequest proto.InternalMessageInfo

// QueryOnboardingParamsResponse is the response for Query/OnboardingParams.
type QueryOnboardingParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryOnboardingParamsResponse) Reset()         { *m = QueryOnboardingParamsResponse{} }
func (m *QueryOnboardingParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOnboardingParamsResponse) ProtoMessage()    {}
func (*QueryOnboardingParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_54be95d4d3143d75, []int{5}
}
func (m *QueryOnboardingParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOnboardingParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOnboardingParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOnboardingParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOnboardingParamsResponse.Merge(m, src)
}
func (m *QueryOnboardingParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOnboardingParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOnboardingParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOnboardingParamsResponse proto.InternalMessageInfo

func (m *QueryOnboardingParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*QueryRegistrationRequest)(nil), "oasyce.onboarding.v1.QueryRegistrationRequest")
	proto.RegisterType((*QueryRegistrationResponse)(nil), "oasyce.onboarding.v1.QueryRegistrationResponse")
	proto.RegisterType((*QueryDebtRequest)(nil), "oasyce.onboarding.v1.QueryDebtRequest")
	proto.RegisterType((*QueryDebtResponse)(nil), "oasyce.onboarding.v1.QueryDebtResponse")
	proto.RegisterType((*QueryOnboardingParamsRequest)(nil), "oasyce.onboarding.v1.QueryOnboardingParamsRequest")
	proto.RegisterType((*QueryOnboardingParamsResponse)(nil), "oasyce.onboarding.v1.QueryOnboardingParamsResponse")
}

func init() { proto.RegisterFile("oasyce/onboarding/v1/query.proto", fileDescriptor_54be95d4d3143d75) }

var fileDescriptor_54be95d4d3143d75 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x41, 0x8b, 0x13, 0x31,
	0x1c, 0xc5, 0x27, 0xba, 0xae, 0x18, 0xf7, 0xb0, 0x86, 0x3d, 0xd4, 0x61, 0x8c, 0xcb, 0xb0, 0xac,
	0x22, 0x25, 0x61, 0xbb, 0x7b, 0xf2, 0xb8, 0xec, 0x51, 0x50, 0xe7, 0xa8, 0xa7, 0x4c, 0x27, 0x64,
	0x03, 0x36, 0x99, 0x4e, 0xd2, 0x62, 0x11, 0x2f, 0x82, 0x77, 0xc1, 0x4f, 0xe0, 0xc1, 0xef, 0xd2,
	0x63, 0xc1, 0x8b, 0x20, 0x88, 0xb4, 0x7e, 0x10, 0x69, 0x26, 0xd5, 0x28, 0x69, 0xab, 0x07, 0x6f,
	0x33, 0xc9, 0x7b, 0xff, 0xf7, 0x9b, 0x79, 0x09, 0x3c, 0xd4, 0xcc, 0x4c, 0xfa, 0x9c, 0x6a, 0x55,
	0x6a, 0xd6, 0x54, 0x52, 0x09, 0x3a, 0x3e, 0xa1, 0xc3, 0x11, 0x6f, 0x26, 0xa4, 0x6e, 0xb4, 0xd5,
	0xe8, 0xa0, 0x55, 0x90, 0x5f, 0x0a, 0x32, 0x3e, 0x49, 0x0f, 0x84, 0x16, 0xda, 0x09, 0xe8, 0xf2,
	0xa9, 0xd5, 0xa6, 0x99, 0xd0, 0x5a, 0xbc, 0xe0, 0x94, 0xd5, 0x92, 0x32, 0xa5, 0xb4, 0x65, 0x56,
	0x6a, 0x65, 0xfc, 0x6e, 0x3c, 0xcb, 0x4e, 0x6a, 0xbe, 0x52, 0xe4, 0x51, 0x85, 0xe0, 0x8a, 0x1b,
	0xe9, 0x35, 0xf9, 0x19, 0xec, 0x3c, 0x5d, 0xe2, 0x15, 0x5c, 0x48, 0x63, 0x1b, 0x97, 0x50, 0xf0,
	0xe1, 0x88, 0x1b, 0x8b, 0x3a, 0xf0, 0x3a, 0xab, 0xaa, 0x86, 0x1b, 0xd3, 0x01, 0x87, 0xe0, 0xfe,
	0x8d, 0x62, 0xf5, 0x9a, 0x4b, 0x78, 0x3b, 0xe2, 0x32, 0xb5, 0x56, 0x86, 0xa3, 0x47, 0x70, 0xaf,
	0x09, 0xd6, 0x9d, 0xf7, 0x66, 0x2f, 0x27, 0xb1, 0x2f, 0x27, 0xe1, 0x84, 0xf3, 0x9d, 0xe9, 0xd7,
	0xbb, 0x49, 0xf1, 0x9b, 0x3b, 0xef, 0xc2, 0x7d, 0x17, 0x75, 0xc1, 0x4b, 0xbb, 0x1d, 0x8c, 0xc1,
	0x5b, 0x81, 0xfa, 0xbf, 0x00, 0x61, 0x98, 0xb9, 0x88, 0xc7, 0x3f, 0x6d, 0x4f, 0x58, 0xc3, 0x06,
	0xc6, 0xc3, 0xe5, 0xcf, 0xe1, 0x9d, 0x35, 0xfb, 0x1e, 0xe7, 0x21, 0xdc, 0xad, 0xdd, 0x8a, 0x07,
	0xc9, 0xe2, 0x20, 0xad, 0xcb, 0x23, 0x78, 0x47, 0xef, 0xcb, 0x55, 0x78, 0xcd, 0x4d, 0x47, 0x1f,
	0x01, 0xdc, 0x0b, 0x59, 0x11, 0x89, 0x8f, 0x59, 0xd7, 0x6e, 0x4a, 0xff, 0x5a, 0xdf, 0x72, 0xe7,
	0x67, 0x6f, 0x3e, 0x7d, 0x7f, 0x7f, 0x85, 0xa0, 0x2e, 0x8d, 0x9e, 0xab, 0xf0, 0x27, 0xd1, 0x57,
	0xbe, 0x90, 0xd7, 0xe8, 0x2d, 0x80, 0x3b, 0xcb, 0x36, 0xd0, 0xf1, 0x86, 0xbc, 0xa0, 0xdc, 0xf4,
	0xde, 0x56, 0x9d, 0xe7, 0xe9, 0x3a, 0x9e, 0x63, 0x74, 0x14, 0xe7, 0xa9, 0x78, 0x69, 0x03, 0x8e,
	0x0f, 0x00, 0xee, 0xff, 0x59, 0x09, 0xea, 0x6d, 0xc8, 0x5a, 0xd3, 0x6f, 0x7a, 0xfa, 0x4f, 0x1e,
	0xcf, 0x7a, 0xe4, 0x58, 0x31, 0xca, 0xe2, 0xac, 0x6d, 0xbb, 0xe7, 0x17, 0xd3, 0x39, 0x06, 0xb3,
	0x39, 0x06, 0xdf, 0xe6, 0x18, 0xbc, 0x5b, 0xe0, 0x64, 0xb6, 0xc0, 0xc9, 0xe7, 0x05, 0x4e, 0x9e,
	0x3d, 0x10, 0xd2, 0x5e, 0x8e, 0x4a, 0xd2, 0xd7, 0x83, 0xd5, 0x84, 0xfe, 0x25, 0x93, 0x8a, 0xbe,
	0x0c, 0x27, 0xb9, 0xcb, 0x5f, 0xee, 0xba, 0x9b, 0x7d, 0xfa, 0x23, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0xf7, 0xe9, 0xa8, 0x8d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Registration queries a registration by address.
	Registration(ctx context.Context, in *QueryRegistrationRequest, opts ...grpc.CallOption) (*QueryRegistrationResponse, error)
	// Debt queries outstanding debt for an address.
	Debt(ctx context.Context, in *QueryDebtRequest, opts ...grpc.CallOption) (*QueryDebtResponse, error)
	// OnboardingParams queries the module parameters.
	OnboardingParams(ctx context.Context, in *QueryOnboardingParamsRequest, opts ...grpc.CallOption) (*QueryOnboardingParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Registration(ctx context.Context, in *QueryRegistrationRequest, opts ...grpc.CallOption) (*QueryRegistrationResponse, error) {
	out := new(QueryRegistrationResponse)
	err := c.cc.Invoke(ctx, "/oasyce.onboarding.v1.Query/Registration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Debt(ctx context.Context, in *QueryDebtRequest, opts ...grpc.CallOption) (*QueryDebtResponse, error) {
	out := new(QueryDebtResponse)
	err := c.cc.Invoke(ctx, "/oasyce.onboarding.v1.Query/Debt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OnboardingParams(ctx context.Context, in *QueryOnboardingParamsRequest, opts ...grpc.CallOption) (*QueryOnboardingParamsResponse, error) {
	out := new(QueryOnboardingParamsResponse)
	err := c.cc.Invoke(ctx, "/oasyce.onboarding.v1.Query/OnboardingParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Registration queries a registration by address.
	Registration(context.Context, *QueryRegistrationRequest) (*QueryRegistrationResponse, error)
	// Debt queries outstanding debt for an address.
	Debt(context.Context, *QueryDebtRequest) (*QueryDebtResponse, error)
	// OnboardingParams queries the module parameters.
	OnboardingParams(context.Context, *QueryOnboardingParamsRequest) (*QueryOnboardingParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Registration(ctx context.Context, req *QueryRegistrationRequest) (*QueryRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registration not implemented")
}
func (*UnimplementedQueryServer) Debt(ctx context.Context, req *QueryDebtRequest) (*QueryDebtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Debt not implemented")
}
func (*UnimplementedQueryServer) OnboardingParams(ctx context.Context, req *QueryOnboardingParamsRequest) (*QueryOnboardingParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnboardingParams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Registration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Registration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.onboarding.v1.Query/Registration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Registration(ctx, req.(*QueryRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Debt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDebtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Debt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.onboarding.v1.Query/Debt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Debt(ctx, req.(*QueryDebtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OnboardingParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOnboardingParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OnboardingParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oasyce.onboarding.v1.Query/OnboardingParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OnboardingParams(ctx, req.(*QueryOnboardingParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oasyce.onboarding.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Registration",
			Handler:    _Query_Registration_Handler,
		},
		{
			MethodName: "Debt",
			Handler:    _Query_Debt_Handler,
		},
		{
			MethodName: "OnboardingParams",
			Handler:    _Query_OnboardingParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oasyce/onboarding/v1/query.proto",
}

func (m *QueryRegistrationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Registration.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDebtRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDebtRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDebtRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDebtResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDebtResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDebtResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Registration.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryOnboardingParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOnboardingParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOnboardingParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryOnboardingParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOnboardingParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOnboardingParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRegistrationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegistrationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Registration.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDebtRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDebtResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Registration.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryOnboardingParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryOnboardingParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRegistrationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Registration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDebtRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDebtRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDebtRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDebtResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDebtResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDebtResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Registration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOnboardingParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOnboardingParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOnboardingParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOnboardingParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOnboardingParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOnboardingParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
